<a href="https://colab.research.google.com/github/sfdxlwcSs/python-Basics/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section One

In [4]:
2+2+5

9

Print Statement

In [3]:
print("NSE Market")

NSE Market


In [3]:
print("Python",2+2,'Hello')

Python 4 Hello


#single line commment


In [4]:
#I am single line comment

# The General order of operations in Python, often remembered by the acronym PEMDAS/BODMAS (though some nuances exist):

Parentheses (): Expressions inside parentheses are evaluated first.

Exponents **: Exponentiation (raising to a power) is evaluated next, from right to left.

Multiplication *, Division /, Floor Division //, Modulo %: These are evaluated from left to right.

Addition +, Subtraction -: These are evaluated from left to right.

Comparison Operators: <, >, <=, >=, ==, !=: These are evaluated next. Chained comparisons like a < b < c are evaluated specially (as discussed before, like (a < b) and (b < c)).

Logical NOT not: This unary operator is evaluated next.

Logical AND and: Evaluated from left to right.

Logical OR or: Evaluated from left to right.

Assignment Operators: =, +=, -=, *=, /=, etc.: These are usually evaluated last (though the expression on the right side is evaluated according to the rules above before the assignment).

Mnemonic:

Parentheses
Exponents
Multiplication, Division, Floor Division, Modulo (from left to right)
Addition, Subtraction (from left to right)
Or, using BODMAS:

Brackets
Orders (exponents/powers, square roots etc.)
Division, Multiplication (from left to right)
Addition, Subtraction (from left to right)
Important Notes:

Python's order is very similar to standard mathematical order of operations.
You can always use parentheses to explicitly control the order of evaluation. This often makes code clearer even if the default order would produce the same result.
Chained comparisons are a special case and are not strictly left-to-right application of binary comparison operators.

In [1]:
import pandas as pd

data = {
    "Country": ["Bangladesh", "Pakistan", "Nigeria", "Ethiopia", "Philippines", "Egypt", "DR Congo", "Vietnam", "Iran", "Turkey"],
    "GDP per Capita (USD)": [2500, 3000, 2200, 1000, 3500, 4000, 500, 4000, 4500, 5000],
    "Population (millions)": [171.5, 251.3, 232.7, 132.1, 114.9, 114.5, 105.8, 100.4, 90.6, 87.3]
}

df = pd.DataFrame(data)
print(df)


       Country  GDP per Capita (USD)  Population (millions)
0   Bangladesh                  2500                  171.5
1     Pakistan                  3000                  251.3
2      Nigeria                  2200                  232.7
3     Ethiopia                  1000                  132.1
4  Philippines                  3500                  114.9
5        Egypt                  4000                  114.5
6     DR Congo                   500                  105.8
7      Vietnam                  4000                  100.4
8         Iran                  4500                   90.6
9       Turkey                  5000                   87.3


Here are examples of how to represent thousand, billion, and trillion in Python using scientific notation:

1. **Thousand**: \(1,000\) can be represented as `1e3`.
   ```python
   thousand = 1e3
   print(thousand)  # Output: 1000.0
   ```

2. **Billion**: \(1,000,000,000\) can be represented as `1e9`.
   ```python
   billion = 1e9
   print(billion)  # Output: 1000000000.0
   ```

3. **Trillion**: \(1,000,000,000,000\) can be represented as `1e12`.
   ```python
   trillion = 1e12
   print(trillion)  # Output: 1000000000000.0
   ```

These examples show how you can use scientific notation to represent large numbers in Python. If you have any other questions or need further examples, feel free to ask!
100e6 (which stands for 100 million).

In [4]:
import pandas as pd
data = {'A': [1, 2, None, 4], 'B': [None, 2, 3, 4]}
df = pd.DataFrame(data)
df



A    B
0  1.0  NaN
1  2.0  2.0
2  NaN  3.0
3  4.0  4.0

In [5]:
print(df.count())  # Output: A    3, B    3

A    3
B    3
dtype: int64


In [6]:
import pandas as pd
s = pd.Series([1, 2, 2, 3, 3, 3, None])
print(s.value_counts())  # Output: 3.0    3, 2.0    2, 1.0    1


3.0    3
2.0    2
1.0    1
Name: count, dtype: int64


In [7]:
import pandas as pd

# Sample DataFrame
data = {
    'A': [1, 2, 2, 3, 3, 3, None],
    'B': ['cat', 'dog', 'cat', 'dog', 'dog', 'cat', 'cat'],
    'C': [True, False, True, True, False, False, True]
}
df = pd.DataFrame(data)

# Applying value_counts() to each column
for column in df.columns:
    print(f"Value counts for column {column}:")
    print(df[column].value_counts(dropna=False))
    print()


Value counts for column A:
A
3.0    3
2.0    2
1.0    1
NaN    1
Name: count, dtype: int64

Value counts for column B:
B
cat    4
dog    3
Name: count, dtype: int64

Value counts for column C:
C
True     4
False    3
Name: count, dtype: int64



In [24]:
print(' '*5+'A'*1)
print(' '*4+'A'*2)
print(' '*3+'A'*3)
print(' '*2+'A'*4)
print(' '*1+'A'*5)

print('\n')

for i in range(1,6):
    print(' '*(6-i)+'A'*i)

x=1
while x <= 5:
    print(' '*(6-x)+'B'*x)
    x += 1  

     A
    AA
   AAA
  AAAA
 AAAAA


     A
    AA
   AAA
  AAAA
 AAAAA
     B
    BB
   BBB
  BBBB
 BBBBB


In [25]:
5/2 # division

2.5

In [26]:
5//2 # quotient

2

In [27]:
5%2 # remainder

1

In [28]:
a='Somnath Sharma'
a[1:-1] # display from 1st to last-1

'omnath Sharm'

In [29]:
a[:] # display all

'Somnath Sharma'

In [30]:
a[1:5] # display from 1st to 5th-1
a[1:5:2] # display from 1st to 5th-1 with step of 2

'on'

In [31]:
a[:-1] # display from 0 to last-1

'Somnath Sharm'

In [ ]:
a[-1] # display last character

'a'

In [34]:
s1="w3","school"
sep="-"
sep.join(s1) # join with separator

'w3-school'

In [36]:
text="Python is a programming language"
print(text.split()) # split by space
type(text.split()) # type of split  


['Python', 'is', 'a', 'programming', 'language']


list

In [58]:
numbers=range(1,10)
print(numbers) # display range
print(list(numbers)) # display range in list
for i in range(0,10):
    print(i) # display range in loop

range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
0
1
2
3
4
5
6
7
8
9


In [40]:
List=['1','2','4','4','5']
for i in List:
    print(i) # display list

List.count('4') # count of 4 in list

1
2
4
4
5


2

In [44]:
List.index('4') # index of 4 in list


2

In [50]:
# conceatenate two lists
List1=['1','2','3']
List2=['4','5','6']
List3=List1+List2
print(List3) # display list 
List3.append('7') # append 7 to list
print(List3) # display list
List3.insert(2,'8') # insert 8 at index 2
List3.pop(2) # remove 8 from index 2
List3.append('9') # add 9 to the end of list

['1', '2', '3', '4', '5', '6']
['1', '2', '3', '4', '5', '6', '7']


In [51]:
# delete List
del List3 # delete List3

In [54]:
# Using Dictionary Objects

# Define a variable
my_text = "A Quick Brown Brown Fox Jumps over the Lazy Dog"

# See how split() works
print(my_text.split())
# Output: ['A', 'Quick', 'Brown', 'Fox', 'Jumps', 'over', 'the', 'Lazy', 'Dog']

# Initialize a dictionary object
# Use {} curly brackets to construct a dictionary object
my_dictionary = {}

# We will perform a word count using the dictionary object
for word in my_text.lower().split():
    if word not in my_dictionary:
        my_dictionary[word] = 1
    else:
        my_dictionary[word] += 1

# The above code builds a frequency table for every word

# Print the output
# Output is key-value pair
print(my_dictionary)
# Output: {'a': 1, 'quick': 1, 'brown': 1, 'fox': 1, 'jumps': 1, 'over': 1, 'the': 1, 'lazy': 1, 'dog': 1}

['A', 'Quick', 'Brown', 'Brown', 'Fox', 'Jumps', 'over', 'the', 'Lazy', 'Dog']
{'a': 1, 'quick': 1, 'brown': 2, 'fox': 1, 'jumps': 1, 'over': 1, 'the': 1, 'lazy': 1, 'dog': 1}


In [57]:
for key,value in my_dictionary.items():
    print(key, value)

a 1
quick 1
brown 2
fox 1
jumps 1
over 1
the 1
lazy 1
dog 1


In [56]:
from collections import defaultdict
# Initialize a dictionary object
my_dictionary2 = defaultdict(int)
# We will perform a word count using the dictionary object
for word in my_text.lower().split():
    my_dictionary2[word] += 1
# The above code builds a frequency table for every word
# Print the output  
# Output is key-value pair
print(my_dictionary2)


defaultdict(<class 'int'>, {'a': 1, 'quick': 1, 'brown': 2, 'fox': 1, 'jumps': 1, 'over': 1, 'the': 1, 'lazy': 1, 'dog': 1})


In [ ]:
words=['Python','is','a','programming','language']
op=[word[0] for word in words] # list comprehension
print(op) # display first letter of each word

['P', 'i', 'a', 'p', 'l']


In [60]:
my_colors = ['red', 'green', 'blue']
op2=[0 if color=='red' else 1 if color=='green' else 2 for color in my_colors]
print(op2) # display 0 for red, 1 for green, 2 for blue

[0, 1, 2]


In [62]:
def empty_fn(x):
    x=5
    return

result=empty_fn(10) # function with no return value
print(result) # display None

None


In [67]:
fun=lambda x,y:x if x>y else y
print(fun(10,20)) # display 20

20


In [63]:
sample_list = [1, 2, 3, 4]
sample_list2 = [5, 6, 7, 8, 9]
sample_tuple = (10, 11, 12)

seq_list1 = list(map(lambda x: x * 2, sample_list))
seq_list2 = list(map(lambda x: x * 2, sample_list2))
seq_tuple = tuple(map(lambda x: x * 2, sample_tuple))

print(seq_list1)   # Output: [2, 4, 6, 8]
print(seq_list2)   # Output: [10, 12, 14, 16, 18]
print(seq_tuple)   # Output: (20, 22, 24)

[2, 4, 6, 8]
[10, 12, 14, 16, 18]
(20, 22, 24)


Here, the iterable you're passing to map() is a tuple containing the lists and the tuple themselves: (sample_list, sample_list2, sample_tuple).

The lambda x: x*2 function is then applied to each item in this tuple. What are the items? They are the entire lists and the entire tuple.

When you multiply a list or a tuple by an integer in Python, it doesn't perform element-wise multiplication. Instead, it creates a new list or tuple by repeating the original sequence that many times.

In [65]:
seq = list(map(lambda x: x*2, (sample_list, sample_list2, sample_tuple)))
seq

[[1, 2, 3, 4, 1, 2, 3, 4],
 [5, 6, 7, 8, 9, 5, 6, 7, 8, 9],
 (10, 11, 12, 10, 11, 12)]

In [69]:
import numpy as np
num=np.arange(1,10,2,dtype=float) # create array with start, stop, step
print(num) # display array

[1. 3. 5. 7. 9.]


In [70]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]]) # create 2D array
print(arr) # display array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
arr.ndim

2

In [72]:
arr.shape # display shape of array

(3, 3)

In [76]:
arr2=np.array([(4,3,4),(1,2,3),(1,2,3)]) # create 2D array
print(arr2) # display array
print(arr2.shape) # display shape of array
print(arr2.ndim) # display dimension of array
print('Size',arr2.size) # display size of array

[[4 3 4]
 [1 2 3]
 [1 2 3]]
(3, 3)
2
Size 9


In [79]:
arr2.dtype # display data type of array
arr2.astype('int') # convert to int32

array([[4, 3, 4],
       [1, 2, 3],
       [1, 2, 3]])

In [82]:
arr2[0:2,0:2] # display 0 to 2nd row and 0 to 2nd column

array([[4, 3],
       [1, 2]])

In [ ]:
arr2[::2] # display alternate rows


array([[4, 3, 4],
       [1, 2, 3]])

In [93]:
arr2[::2,::2] # display alternate rows and columns

array([[4, 4],
       [1, 3]])

In [ ]:
arr2[0][1] # display 0th row and 1st column

np.int64(3)

In [86]:
a1d = np.array([1, 2, 3, 4, 5])
a1d[0:3] # display 0 to 3rd element


array([1, 2, 3])

In [87]:
a1d[0:3] = 10 # assign 10 to 0 to 3rd element

In [88]:
a1d

array([10, 10, 10,  4,  5])

In [ ]:
a1d[:2] # display 0 to 2nd element

array([10, 10])

In [91]:
a1d[::2] 

array([10, 10,  5])

Use element-wise multiplication (*) when you want to multiply corresponding elements of arrays with the same shape.
Use dot product (np.dot() or @) for vector-vector inner products or matrix multiplication, where the dimensions must be compatible according to the rules of linear algebra.

In [94]:
new_series=pd.Series(np.array([1,2,3,4,5]),index=['a','b','c','d','e']) # create series with index
print(new_series) # display series

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [95]:
my_dic={'a':1,'b':2,'c':3,'d':4,'e':5}
new_series2=pd.Series(my_dic) # create series from dictionary
print(new_series2) # display series

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [96]:
# Both sort() and sorted() are used to sort lists in Python, but they have some key differences:1. sort() methodApplies to: Only lists.Modifies: The original list in place.  It doesn't return a new list; it returns None.Usage: list.sort(key=..., reverse=...)
# Example:
my_list = [3, 1, 4, 1, 5, 9, 2, 6]
my_list.sort()  # Sorts the list in place
print(my_list)    # Output: [1, 1, 2, 3, 4, 5, 6, 9]

my_list.sort(reverse=True)  # Sort in descending order
print(my_list)    # Output: [9, 6, 5, 4, 3, 2, 1, 1]

my_list = ['apple', 'banana', 'cherry', 'date']
my_list.sort(key=len)  # Sort by length of the strings
print(my_list)    # Output: ['date', 'apple', 'banana', 'cherry']
# 2. sorted() functionApplies to: Any iterable (lists, tuples, strings, dictionaries, etc.).Modifies: Does not modify the original iterable. 
# Returns a new sorted list.Usage: sorted(iterable, key=..., reverse=...)

my_list = [3, 1, 4, 1, 5, 9, 2, 6]
new_list = sorted(my_list)  # Returns a new sorted list
print(my_list)    # Output: [3, 1, 4, 1, 5, 9, 2, 6] (original is unchanged)
print(new_list)    # Output: [1, 1, 2, 3, 4, 5, 6, 9]

my_tuple = (5, 2, 8, 1, 9)
sorted_tuple = sorted(my_tuple)  # Returns a new sorted list
print(my_tuple)      # Output: (5, 2, 8, 1, 9) (original is unchanged)
print(sorted_tuple)  # Output: [1, 2, 5, 8, 9]

my_string = "hello"
sorted_string = sorted(my_string) # Returns a new sorted list of characters
print(my_string)    # Output: hello (original is unchanged)
print(sorted_string)  # Output: ['e', 'h', 'l', 'l', 'o']
#Key Parameters for both sort() and sorted():key:  A function that serves as a key for the sort comparison.  The items are sorted based on the result of this function applied to each item.reverse: A boolean value. If True, the list is sorted in descending order.When to use which:Use list.sort() when you want to modify the original list in place and don't need a new sorted list.  It's generally more efficient if you don't need to keep the original order.Use sorted(iterable) when you want to get a new sorted list without modifying the original iterable, or when you're working with an iterable other than a list (like a tuple or string).

[1, 1, 2, 3, 4, 5, 6, 9]
[9, 6, 5, 4, 3, 2, 1, 1]
['date', 'apple', 'banana', 'cherry']
[3, 1, 4, 1, 5, 9, 2, 6]
[1, 1, 2, 3, 4, 5, 6, 9]
(5, 2, 8, 1, 9)
[1, 2, 5, 8, 9]
hello
['e', 'h', 'l', 'l', 'o']


String Immutability

In Python, a string is considered an immutable data type. This means that once a string is created, its contents cannot be changed. You can't modify a string in place.

Here's a breakdown of what that means:

Cannot be changed directly: You can't alter individual characters within an existing string.
New strings are created: Any operation that appears to modify a string (e.g., concatenation, slicing with modification) actually creates a brand new string object in memory. The original string remains unchanged.
Efficiency: Immutability can offer some performance benefits in certain situations, as Python can optimize memory allocation and handling of immutable objects.

In [97]:
my_string = "hello"

# Attempting to change a character directly will result in an error
# my_string[0] = 'j'  # This will raise a TypeError: 'str' object does not support item assignment

# Concatenation creates a new string
new_string = my_string + " world"
print(new_string)  # Output: hello world
print(my_string)   # Output: hello (the original string is unchanged)

# Slicing and "modification" also create a new string
modified_string = my_string[:2] + "J" + my_string[3:]
print(modified_string)  # Output: heJlo
print(my_string)        # Output: hello (the original string is unchanged)

hello world
hello
heJlo
hello


Lists in Python are mutable. This means that once a list is created, you can change its contents directly. You can add, remove, or modify elements within an existing list without creating a new list object (though some operations might implicitly create new lists).   



In [99]:
# Lists are mutable
my_list = [1, 2, 3, 4]
print(f"Original list: {my_list}")

# You can change an element by index
my_list[0] = 10
print(f"List after changing element at index 0: {my_list}")  # Output: [10, 2, 3, 4]

# You can add elements
my_list.append(5)
print(f"List after appending: {my_list}")  # Output: [10, 2, 3, 4, 5]

# You can remove elements
del my_list[1]
print(f"List after deleting element at index 1: {my_list}")  # Output: [10, 3, 4, 5]

# You can extend the list
my_list.extend([6, 7])
print(f"List after extending: {my_list}")  # Output: [10, 3, 4, 5, 6, 7]

Original list: [1, 2, 3, 4]
List after changing element at index 0: [10, 2, 3, 4]
List after appending: [10, 2, 3, 4, 5]
List after deleting element at index 1: [10, 3, 4, 5]
List after extending: [10, 3, 4, 5, 6, 7]


Cross tables are used to analyze the association between categorical variables. You can use the numbers in the table to calculate various statistics, such as chi-square, to test the statistical significance of the relationship.
Cross Table (Crosstabulation)

A cross table is a table that displays the frequency distribution of two or more categorical variables. It shows how these variables relate to each other. It's a fundamental tool for examining relationships between categorical data.

Key Points

Categorical Variables: Cross tables are used with variables that have a limited number of distinct categories or groups (e.g., gender, education level, region, opinion).

Frequency Distribution: The table shows how many observations fall into each combination of categories.

Relationship: By examining the patterns in the table, you can gain insights into whether there's an association between the variables.

In [100]:
import pandas as pd

# Sample data in a dictionary
data = {
    'Gender': ['Female', 'Female', 'Female', 'Female', 'Female', 'Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male'],
    'Product': ['A', 'B', 'B', 'A', 'B', 'C', 'A', 'A', 'C', 'B', 'C', 'C']
}

# Create a DataFrame
df = pd.DataFrame(data)

# Create a cross table
cross_table = pd.crosstab(df['Gender'], df['Product'])

# Print the cross table
print(cross_table)

Product  A  B  C
Gender          
Female   2  3  1
Male     2  1  3


In [ ]:
# A pivot table is a powerful tool in data analysis that allows you to summarize, aggregate, and reorganize data in a DataFrame. 
# It helps you transform data into a more meaningful format by grouping and aggregating values based on specified criteria.

# ### Key Features of Pivot Tables:
# 1. **Grouping**: You can group data based on one or more columns.
# 2. **Aggregation**: You can perform various aggregation functions like sum, mean, count, etc., on grouped data.
# 3. **Reorganization**: You can rearrange data to make it easier to analyze.

# ### Example Usage
# Let's create a pivot table using a sample DataFrame:


import pandas as pd

# Sample DataFrame
data = {
    'Date': ['2025-05-01', '2025-05-01', '2025-05-02', '2025-05-02', '2025-05-03'],
    'Category': ['A', 'B', 'A', 'B', 'A'],
    'Sales': [100, 150, 200, 250, 300]
}
df = pd.DataFrame(data)

# Creating a pivot table
pivot_table = df.pivot_table(values='Sales', index='Date', columns='Category', aggfunc='sum')
print(pivot_table)
# ```

# ### Output
# ```
# Category        A      B
# Date                    
# 2025-05-01  100.0  150.0
# 2025-05-02  200.0  250.0
# 2025-05-03  300.0    NaN
```

### Explanation:
# - **values='Sales'**: Specifies the column to aggregate.
# - **index='Date'**: Specifies the column to group by (rows).
# - **columns='Category'**: Specifies the column to group by (columns).
# - **aggfunc='sum'**: Specifies the aggregation function (sum in this case).

# ### Aggregation Functions:
# You can use various aggregation functions like:
# - `sum`: Sum of values.
# - `mean`: Average of values.
# - `count`: Count of values.
# - `min`: Minimum value.
# - `max`: Maximum value.

# ### Customizing Pivot Tables:
# You can customize pivot tables further by adding multiple indices or columns, and using different aggregation functions.



In [102]:
import random

random.randint(5, 9)

7

In [103]:
def add_student(students):
    """Adds a new student with their name and marks."""
    name = input("Enter student name: ")
    marks = float(input("Enter student marks: "))  # Use float for marks
    students[name] = marks

def update_marks(students):
    """Updates the marks of an existing student."""
    name = input("Enter student name to update: ")
    if name in students:
        new_marks = float(input("Enter new marks: "))  # Use float for marks
        students[name] = new_marks
    else:
        print("Student not found.")

def calculate_average_marks(students):
    """Calculates the average marks of all students."""
    if not students:  # Check if the dictionary is empty
        return 0.0  # Return 0.0 for empty dictionary to avoid error
    total_marks = sum(students.values())
    return total_marks / len(students)

def display_students(students):
    """Displays all student names with their marks."""
    if not students:
        print("No students to display.")
        return
    print("Student Marks:")
    for name, marks in students.items():
        print(f"{name}: {marks}")

# Main program
students = {}  # Use a dictionary to store student names and marks

while True:
    print("\nStudent Marks System Menu:")
    print("1. Add a new student")
    print("2. Update student marks")
    print("3. Calculate average marks")
    print("4. Display all students")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == '1':
        add_student(students)
    elif choice == '2':
        update_marks(students)
    elif choice == '3':
        average = calculate_average_marks(students)
        print(f"Average marks: {average:.2f}")  # Format the output
    elif choice == '4':
        display_students(students)
    elif choice == '5':
        break
    else:
        print("Invalid choice. Please try again.")


Student Marks System Menu:
1. Add a new student
2. Update student marks
3. Calculate average marks
4. Display all students
5. Exit

Student Marks System Menu:
1. Add a new student
2. Update student marks
3. Calculate average marks
4. Display all students
5. Exit

Student Marks System Menu:
1. Add a new student
2. Update student marks
3. Calculate average marks
4. Display all students
5. Exit


In [104]:
students

{'ss': 1.0, 'dd': 3.0}

In [108]:
n=202
a=str(n)
b=a[-1]
print(b) # display last digit
print(a[0])

2
2


palindrome

In [110]:
n = 12345
reversed_string = str(n)[::-1]
print(reversed_string)  # Output: '54321'


54321


String Slicing in Python
String slicing allows you to access a portion of a string using a specific syntax: string[start:end:step].

start: The starting index of the slice.
end: The ending index of the slice (not included in the slice).
step: The step size, which determines how the slice is taken.
Reversing a String with [::-1]
str(n)[::-1]: This syntax uses slicing to reverse the string.
start: Not specified, so it defaults to the beginning of the string.
end: Not specified, so it defaults to the end of the string.
step: -1, which means the slice is taken from end to start, effectively reversing the string.

In [109]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def is_palindrome(n):
    return str(n) == str(n)[::-1]

# Example usage
number = 131
if is_prime(number) and is_palindrome(number):
    print(f"{number} is both a prime and a palindrome number.")
else:
    print(f"{number} is not both a prime and a palindrome number.")


131 is both a prime and a palindrome number.


In [111]:
def is_prime_basic(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

# Example usage
print(is_prime_basic(29))  # Output: True
print(is_prime_basic(28))  # Output: False


True
False


In [112]:
import math

def is_prime_optimized(n):
    if n <= 1:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Example usage
print(is_prime_optimized(29))  # Output: True
print(is_prime_optimized(28))  # Output: False


True
False


In [115]:
%pip install sympy

   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   --------------------- ------------------ 3.4/6.3 MB 18.1 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 16.8 MB/s eta 0:00:00
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   --------------------------------------- 536.2/536.2 kB 12.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [116]:
from sympy import isprime

def is_prime_sympy(n):
    return isprime(n)

# Example usage
print(is_prime_sympy(29))  # Output: True


True


dfSource['Request_Type__c'].count()

Counts the number of non-null values in the 'Request_Type__c' column of the DataFrame dfSource.

It does not include NaN (Not a Number) or missing values in the count.

Returns a single numerical value (an integer).

dfSource['Request_Type__c'].value_counts()

Counts the frequency of each unique value in the 'Request_Type__c' column.

Returns a Pandas Series.

The index of the Series contains the unique values from the 'Request_Type__c' column.

The values of the Series represent the number of times each unique value appears in the column.

In [41]:
# %pip install openpyxl

import pandas as pd
import numpy as np

dfSource = pd.read_excel('Case_Queue_Assignment__c-149.xlsx', sheet_name='Sheet1')
dfSource.head()
RequestType=dfSource['Request_Type__c'].unique() # display unique values in column
print('length of unique',len(RequestType)) # display count of unique values
print('unique',dfSource['Request_Type__c'].unique()) # display unique values in column
print('non null',dfSource['Request_Type__c'].count()) # display count of non null values

print(dfSource['Request_Type__c'].value_counts()) # display count of unique values of each type
nullVal=dfSource[dfSource['Request_Type__c'].isnull()] # display null values in column

type(RequestType) # display type of unique values
df2=pd.read_excel('Case_Queue_Assignment__c-145K.xlsx', sheet_name='Sheet1')
df2.head()
RequestTypedf2=df2['Request_Type__c'].unique() # display unique values in column
print(len(RequestTypedf2)) # display count of unique values
nullVal.head(10) # display null values in column
# dataSource.drop(dataSource[dataSource['Request_Type__c'].isnull()].index, inplace=True) # remove null values from column
dfSource.dropna(subset=['Request_Type__c'], inplace=True) # remove null values from column
# dfSource.dropna(subset=['Request_Type__c'], inplace=True) # remove null values from column
df3=pd.merge(dfSource, df2, on='Request_Type__c', how='left')
df3.head()




# export to excel

length of unique 123
unique ['Compensation - AIP/SIP Plan Review'
 'Compensation - Employee Market Analysis Request'
 'Compensation - Job Analysis Request' 'Compensation - LTIP Request'
 'Compensation - Market Data Request' 'Completion Credit'
 'Employee Data Changes' 'Talent - Succession' 'Talent - Other'
 'Employee & Organizational Data' 'Login' 'General Inquiry' 'Learning'
 'Recruiting - Recruiting and Offers'
 'Recruiting- Pre-employment Screening' 'Recruiting - Onboarding'
 'Recruiting - Manage Pending Hires' 'Recruiting Requisition Changes'
 'Workflows & Approvals' 'Recruiting Requisition Approval Reroute'
 'Onboarding & 1-9 Activity Reassignment' 'Compensation Form Reroute'
 'Talent Form Reroute' 'Workflow Approval Reroute'
 "Workflow Escalation (Manager's Manager)"
 'Recruiting Offer Approval Reroute' 'Other Workflow & Approvals Reroute'
 'Attendance Tracking' 'Learning Management System Data Changes'
 'Time Card Edits' 'Accruals Balance' 'Safety Boots' 'Uniform'
 'Union Dues' 

Id        Name  \
0  a0cQJ000000aDY8YAM  CQA-000295   
1  a0cQJ000000aDY9YAM  CQA-000296   
2  a0cQJ000000aDYAYA2  CQA-000297   
3  a0cQJ000000aDYBYA2  CQA-000298   
4  a0cQJ000000aDYCYA2  CQA-000299   

                                      Combination__c  Is_Active__c  \
0  HR-HRC - Questions-Compensation - AIP/SIP Plan...          True   
1  HR-HRC - Questions-Compensation - Employee Mar...          True   
2  HR-HRC - Questions-Compensation - Job Analysis...          True   
3     HR-HRC - Questions-Compensation - LTIP Request          True   
4  HR-HRC - Questions-Compensation - Market Data ...          True   

  Request_Reason__c Request_Sub_Reason__c  \
0                HR       HRC - Questions   
1                HR       HRC - Questions   
2                HR       HRC - Questions   
3                HR       HRC - Questions   
4                HR       HRC - Questions   

                                   Request_Type__c    Queue_Name__c  \
0               Compensation - AIP/SIP Plan Review   COE - Comp CoE   
1  Compensation - Employee Market Analysis Request   COE - Comp CoE   
2              Compensation - Job Analysis Request   COE - Comp CoE   
3                      Compensation - LTIP Request  COE - Exec Comp   
4               Compensation - Market Data Request   COE - Comp CoE   

         Chat_Queue__c Request Reason Request Sub Reason  Case Queue Name  \
0  Tier1 Generalist-HR             HR    HRC - Questions   COE - Comp CoE   
1  Tier1 Generalist-HR             HR    HRC - Questions   COE - Comp CoE   
2  Tier1 Generalist-HR             HR    HRC - Questions   COE - Comp CoE   
3  Tier1 Generalist-HR             HR    HRC - Questions  COE - Exec Comp   
4  Tier1 Generalist-HR             HR    HRC - Questions   COE - Comp CoE   

                              Concatenate New Object  \
0  HR|HRC - Questions|Compensation - AIP/SIP Plan...   
1  HR|HRC - Questions|Compensation - Employee Mar...   
2  HR|HRC - Questions|Compensation - Job Analysis...   
3     HR|HRC - Questions|Compensation - LTIP Request   
4  HR|HRC - Questions|Compensation - Market Data ...   

                                    Compare with MDT  \
0  HR|HRC - Questions|Compensation - AIP/SIP Plan...   
1  HR|HRC - Questions|Compensation - Employee Mar...   
2  HR|HRC - Questions|Compensation - Job Analysis...   
3     HR|HRC - Questions|Compensation - LTIP Request   
4  HR|HRC - Questions|Compensation - Market Data ...   

                   Concatenate New Object with Queue  \
0  HR|HRC - Questions|Compensation - AIP/SIP Plan...   
1  HR|HRC - Questions|Compensation - Employee Mar...   
2  HR|HRC - Questions|Compensation - Job Analysis...   
3  HR|HRC - Questions|Compensation - LTIP Request...   
4  HR|HRC - Questions|Compensation - Market Data ...   

                                          Comparison Comments  
0                                                NaN      New  
1                                                NaN      New  
2                                                NaN      New  
3  HR|HRC - Questions|Compensation - LTIP Request...      NaN  
4                                                NaN      New

In [42]:
dfSource['Request_Type__c'].isnull().sum()

np.int64(0)

In [43]:
df3.isnull().sum() # check for null values


Id                                     0
Name                                   0
Combination__c                         0
Is_Active__c                           0
Request_Reason__c                      0
Request_Sub_Reason__c                  0
Request_Type__c                        0
Queue_Name__c                          0
Chat_Queue__c                          0
Request Reason                         6
Request Sub Reason                     6
Case Queue Name                        6
Concatenate New Object                 6
Compare with MDT                       7
Concatenate New Object with Queue      6
Comparison                           189
Comments                             437
dtype: int64

In [44]:
drop_list = ['Comparison', 'Concatenate New Object with Queue', 'Compare with MDT','Concatenate New Object']
df3.drop(columns=drop_list, inplace=True)
df3.head()

Id        Name  \
0  a0cQJ000000aDY8YAM  CQA-000295   
1  a0cQJ000000aDY9YAM  CQA-000296   
2  a0cQJ000000aDYAYA2  CQA-000297   
3  a0cQJ000000aDYBYA2  CQA-000298   
4  a0cQJ000000aDYCYA2  CQA-000299   

                                      Combination__c  Is_Active__c  \
0  HR-HRC - Questions-Compensation - AIP/SIP Plan...          True   
1  HR-HRC - Questions-Compensation - Employee Mar...          True   
2  HR-HRC - Questions-Compensation - Job Analysis...          True   
3     HR-HRC - Questions-Compensation - LTIP Request          True   
4  HR-HRC - Questions-Compensation - Market Data ...          True   

  Request_Reason__c Request_Sub_Reason__c  \
0                HR       HRC - Questions   
1                HR       HRC - Questions   
2                HR       HRC - Questions   
3                HR       HRC - Questions   
4                HR       HRC - Questions   

                                   Request_Type__c    Queue_Name__c  \
0               Compensation - AIP/SIP Plan Review   COE - Comp CoE   
1  Compensation - Employee Market Analysis Request   COE - Comp CoE   
2              Compensation - Job Analysis Request   COE - Comp CoE   
3                      Compensation - LTIP Request  COE - Exec Comp   
4               Compensation - Market Data Request   COE - Comp CoE   

         Chat_Queue__c Request Reason Request Sub Reason  Case Queue Name  \
0  Tier1 Generalist-HR             HR    HRC - Questions   COE - Comp CoE   
1  Tier1 Generalist-HR             HR    HRC - Questions   COE - Comp CoE   
2  Tier1 Generalist-HR             HR    HRC - Questions   COE - Comp CoE   
3  Tier1 Generalist-HR             HR    HRC - Questions  COE - Exec Comp   
4  Tier1 Generalist-HR             HR    HRC - Questions   COE - Comp CoE   

  Comments  
0      New  
1      New  
2      New  
3      NaN  
4      New

In [45]:
df3.describe().T # display summary of data

count unique  \
Id                      620    148   
Name                    620    148   
Combination__c          620    148   
Is_Active__c            620      1   
Request_Reason__c       620      9   
Request_Sub_Reason__c   620     47   
Request_Type__c         620    122   
Queue_Name__c           620     13   
Chat_Queue__c           620      2   
Request Reason          614      9   
Request Sub Reason      614     47   
Case Queue Name         614     11   
Comments                183      3   

                                                                     top freq  
Id                                                    a0cQJ000000aDbVYAU   22  
Name                                                          CQA-000404   22  
Combination__c         My Rewards-Compensation & Rewards-Ask HR a Que...   22  
Is_Active__c                                                        True  620  
Request_Reason__c                                               Managers  160  
Request_Sub_Reason__c                             Performance Management   44  
Request_Type__c                                        Ask HR a Question  484  
Queue_Name__c                                        Tier1 Generalist-HR  491  
Chat_Queue__c                                        Tier1 Generalist-HR  593  
Request Reason                                                  Managers  160  
Request Sub Reason                                Performance Management   44  
Case Queue Name                                      Tier1 Generalist-HR  491  
Comments                                                             New  100

In [48]:
df3[df3['Request_Type__c'].isnull()]

Empty DataFrame
Columns: [Id, Name, Combination__c, Is_Active__c, Request_Reason__c, Request_Sub_Reason__c, Request_Type__c, Queue_Name__c, Chat_Queue__c, Request Reason, Request Sub Reason, Case Queue Name, Comments]
Index: []

In [47]:
df3.to_excel('test3.xlsx', index=False)