<span style="font-family: Arial; font-weight:bold;font-size:1em;color:#f0f0f0;">           
    <span style="font-family: Arial; font-weight:bold;font-size:3em;color:#0a7a78;">             Python for Data Science 
       -- Graded Assessment 

   <span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;">Time:3hrs                                                                                            &emsp;$\;\;\;\;\;\;$$\;\;\;\;\;\;$$\;\;\;\;\;\;$$\;\;\;\;\;\;$$\;\;\;\;\;\;$$\;\;\;\;\;\;$$\;\;\;\;\;\;$$\;\;\;\;\;\;$$\;\;\;\;\;\;$$\;\;\;\;\;\;$$\;\;\;\;\;\;$ $\;\;\;\;\;\;$$\;\;\;\;\;\;$$\;\;\;\;\;\;$Total Marks:  40 

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;"> Section -A

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;">1. (A) Write python program to reverse a given string using slicing.(1 mark)

**Sample:**     

             INPUT:'Welcome'

             OUTPUT:'emocleW'

In [1]:
data=input('Enter a String-')
revData=data[::-1]
print(revData)

Enter a String-Welcome
emocleW


<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;">1. B) Write a python program to find the sum of the Series: 1 + 1/2 + 1/3 + ….. + 1/N.          (2 marks)

#### Python Code:


In [2]:
n=int(input('Enter a range-'))
sumofNum=sum([1/x for x in range(1,(1+n)) ])
sumofNum

Enter a range-3


1.8333333333333333

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;">1. C)Write a program to divide 5 by 2 so that the output is 		(2 mark)

	a) 2

	b) 2.5


In [3]:
n1=5
n2=2
op1=n1/n2
print(op1)
op2=round(n1/n2)
print(op2)

2.5
2


<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;">2. A) Write a program to print the following number pattern.( 3 marks)
  ##  1 
  ##  1 2 
  ##  1 2 3 
  ##  1 2 3 4 
  ##  1 2 3 4 5


In [4]:
n=int(input('Enter a range-'))
def printPattern(n):
    for i in range(1,(n+1)):
        print(' '.join(str(num) for num in range(1,i+1)))

printPattern(n)


Enter a range-5
1
1 2
1 2 3
1 2 3 4
1 2 3 4 5


<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;"> 2. B) Write a python program to print all letters except 'e' and 'l' in the string 'greatlearning' using while loop. (2 marks)

In [9]:
inp='greatlearning'

out=''
i=0
while i< len(inp):
    if (inp[i]!='e' and inp[i]!='l'):
        out+=inp[i]
    i=i+1
    
print('result',out)

    

result gratarning


<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;"> 3. (A) Given two lists of integers, create a third list by user defined function such that it should contain only odd numbers from the first list and even numbers from the second list? 								(3 marks)

	* list1 = [10, 20, 23, 11, 17]
	* list2 = [13, 43, 24, 36, 12]
    
Sample Output:

Merged List :
[23, 11, 17, 24, 36, 12]



In [19]:
combinedList=[]
def oddEven(list1,list2):
    combinedList=[x for x in list1 if x%2!=0] + [y for y in list2  if y%2==0]
    return combinedList

list1 = [10, 20, 23, 11, 17]
list2 = [13, 43, 24, 36, 12]

mergedList=oddEven(list1,list2)
mergedList
    

[23, 11, 17, 24, 36, 12]

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;">3. B) Create a dictionary with the keys 1,2 and 3 with values 'Learning', 'For' and {A: Life, B:To , C: Great} respectively and update the value of 2 to 'Great Learning'. (2 marks)


In [35]:
inputDic={'1':'Learning' ,'2':'For','3':{'A: Life, B:To , C: Great'} }
print(inputDic.values())



dict_values(['Learning', 'For', {'A: Life, B:To , C: Great'}])


In [36]:
inputDic['2']='Great Learning'

In [37]:
print('🚀Output',inputDic.values())

🚀Output dict_values(['Learning', 'Great Learning', {'A: Life, B:To , C: Great'}])


<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;">4. (A) Create a scientific calculator using user defined function in python. The calculator should give a menu to the user asking the type of mathematical operation to be performed (1. Addition  2. Subtraction 3. Mulitiplication and 4. Division.  According to the choice of the user, operations are performed on the numbers entered. Any innovation in this basic calculator model will be given marks. 		(3 marks)

SAMPLE INPUT:
SCIENTIFIC CALCULATOR
1.	ADDITION 	2. SUBTRATION	3. MULTIPLICATION	4. DIVISION
Please select an option of your choice4
Enter the first number23
Enter the second number56
SAMPLE OUTPUT:
The division of the first number with the second number is 0.4107142857142857


In [1]:

def customCalculator():
    operations=['Press 1  Addition','Press 2  Subtraction','Press 3  Mulitiplication','Press 4  Division']
    print('Below are the available Operation🧮🧮')
    print('Operations',operations)
    print('Please select an option of your choice.')
    userInput=int(input('mathematical operation to be performed'))
    n1=int(input('Enter the first number'))
    n2=int(input('Enter the second number'))
    if userInput==1:
         return print('The addition of the first number with the second number is ',n1+n2)
    elif userInput==2:
         return print('The substraction of the first number with the second number is ',n1-n2)
    elif userInput==3:
         return print('The multiplication of the first number with the second number is ',n1*n2)    
    elif userInput==4:
         return print('The division of the first number with the second number is ',n1/n2)
    else:
         return print('Not a valid operation')



customCalculator()
    


Below are the available Operation🧮🧮
Operations ['Press 1  Addition', 'Press 2  Subtraction', 'Press 3  Mulitiplication', 'Press 4  Division']
Please select an option of your choice.
The multiplication of the first number with the second number is  16


<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;">4. B) Write a program to print the sum of squares of first 10 natural numbers using lambda, map and reduce.(2 marks)



In [54]:
numbers=list(range(1,11))
print(numbers)
squaresOfNumber=list(map(lambda x:x**2,numbers))
from functools import reduce
result=reduce(lambda x,y:x+y,squaresOfNumber)
result

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


385

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;"> Section -B

In [ ]:
import numpy as np 
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import math
import seaborn as sns

###     5.   Do the following:  (5 Marks)
        (i)  Create an array of 12 random integers using step size of 1.
        (ii) Use the array created above to increase all the elements in the array by 1.
        (iii)Sort the elements in the array using in-built function.
        (iv) Reshape the array to 3 rows and 4 columns.
        (v)  Display the element in the 2nd row 3rd column.

In [71]:
randomArr=np.random.randint(0,12,size=12)
randomArr


<IPython.core.display.Javascript object>

array([ 1, 11,  3,  1,  8,  0,  0,  4,  0,  4,  3,  3])

In [72]:
randomArrIncremented=randomArr+1
randomArrIncremented


array([ 2, 12,  4,  2,  9,  1,  1,  5,  1,  5,  4,  4])

In [76]:
randomArrSorted=np.sort(randomArrIncremented)
print(randomArrSorted)
randomArrReshaped=randomArrSorted.reshape(3,4)
print(randomArrReshaped)
print('Display the element in the 2nd row 3rd column.',randomArrReshaped[1,2])


<IPython.core.display.Javascript object>

[ 1  1  1  2  2  4  4  4  5  5  9 12]
[[ 1  1  1  2]
 [ 2  4  4  4]
 [ 5  5  9 12]]
Display the element in the 2nd row 3rd column. 4


#### <span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;">6.) Use the following data for answering the question:<br>
raw_data = {'Name': ['Carly','Rachel','Nicky','Wendy','Judith','Christin','Roy'],<br>
'Birth_Month':['January','September','September','November','February','June','March'],<br>
'Origin':['UK','Spain','Jamaica','Italy','France','UK','US'],<br>
'Age':[27,28,28,22,19,20,19],<br>
'Gender':['F','F','F','F','M','M','M']}

#### <span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;"> 6.A) Create a data frame and assign it to a variable called the person. Don't forget to include the names of the columns in the order presented in the dictionary('Name', 'Birth_Month', 'Origin'...) and also keep 'Name' as index for dataframe   (2 marks)
    


In [85]:
raw_data = {'Name': ['Carly','Rachel','Nicky','Wendy','Judith','Christin','Roy'],
'Birth_Month':['January','September','September','November','February','June','March'],
'Origin':['UK','Spain','Jamaica','Italy','France','UK','US'],
'Age':[27,28,28,22,19,20,19],
'Gender':['F','F','F','F','M','M','M']}
print(raw_data['Name'])
person=pd.DataFrame(raw_data,columns=['Name','Birth_Month','Origin','Age','Gender'],index=raw_data['Name'])

person

['Carly', 'Rachel', 'Nicky', 'Wendy', 'Judith', 'Christin', 'Roy']


<IPython.core.display.Javascript object>

Name Birth_Month   Origin  Age Gender
Carly        Carly     January       UK   27      F
Rachel      Rachel   September    Spain   28      F
Nicky        Nicky   September  Jamaica   28      F
Wendy        Wendy    November    Italy   22      F
Judith      Judith    February   France   19      M
Christin  Christin        June       UK   20      M
Roy            Roy       March       US   19      M

---------

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;"> 6. B. Select and display the information of people born before September (1 mark)


In [92]:
include=['January','February','June','March']
person[person['Birth_Month'].isin(include)]

Name Birth_Month  Origin  Age Gender
Carly        Carly     January      UK   27      F
Judith      Judith    February  France   19      M
Christin  Christin        June      UK   20      M
Roy            Roy       March      US   19      M

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;"> 6.C. Display the records of people born in September and are in Age group 20 to 30 (Both numbers are included) (2 mark)

In [94]:
person[(person['Birth_Month']=='September') & (person['Age']>=20) & (person['Age']<=30)]

Name Birth_Month   Origin  Age Gender
Rachel  Rachel   September    Spain   28      F
Nicky    Nicky   September  Jamaica   28      F

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;"> 7.)Use the dataset Data.csv for the following questions.

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;"> 7.A. Write a block of code to display the average annual income and average credit score for both males and females under each age group in tabular form.(3 Marks)

In [23]:
import pandas as pd ## Exam dataset not available


# Sample DataFrame
data = {'AgeGroup': ['18-24', '18-24', '25-34', '25-34', '35-44', '35-44', '18-24'],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male'],
        'AnnualIncome': [30000, 25000, 40000, 35000, 50000, 45000, 28000],
        'CreditScore': [700, 680, 750, 720, 800, 780, 690],
        'Id': [1, 2, 3, 4, 5, 6, 7],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio'],
        'CityId': [1, 2, 3, 4, 5, 6, 7],
        'Spending Score': [75, 80, 85, 90, 95, 100, 70]
        }
df = pd.DataFrame(data)
print(df)

# Group by 'AgeGroup' and 'Gender', and calculate multiple aggregations
grouped_df = df.groupby(['AgeGroup', 'Gender']).agg(
    AvgIncome=('AnnualIncome', 'mean'),
    AvgCreditScore=('CreditScore', 'mean')
)

print(grouped_df)


  AgeGroup  Gender  AnnualIncome  CreditScore  Id          City  CityId  \
0    18-24    Male         30000          700   1      New York       1   
1    18-24  Female         25000          680   2   Los Angeles       2   
2    25-34    Male         40000          750   3       Chicago       3   
3    25-34  Female         35000          720   4       Houston       4   
4    35-44    Male         50000          800   5       Phoenix       5   
5    35-44  Female         45000          780   6  Philadelphia       6   
6    18-24    Male         28000          690   7   San Antonio       7   

   Spending Score  
0              75  
1              80  
2              85  
3              90  
4              95  
5             100  
6              70  
                 AvgIncome  AvgCreditScore
AgeGroup Gender                           
18-24    Female    25000.0           680.0
         Male      29000.0           695.0
25-34    Female    35000.0           720.0
         Male      40000

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;">  7.B. Write a code snippet to display id, gender, age annual income, credit and spending score for all the customers who are residing in the cities with ids 1 and 5. (2 Marks) 

In [31]:
import pandas as pd
# Filter the DataFrame to include only customers residing in cities with Ids 1 and 5
filtered_df = df[(df['CityId'] == 1) | (df['CityId'] == 5)] 

# Select the desired columns
selected_columns = ['Id', 'Gender', 'AgeGroup', 'AnnualIncome', 'CreditScore', 'Spending Score']

# Display the filtered and selected data
print(filtered_df[selected_columns]) 


   Id Gender AgeGroup  AnnualIncome  CreditScore  Spending Score
0   1   Male    18-24         30000          700              75
4   5   Male    35-44         50000          800              95


In [32]:
import pandas as pd

# Create a Pandas DataFrame from the given data
df = pd.DataFrame(data)

# Filter the DataFrame to include only customers residing in cities with Ids 1 and 5
filtered_df = df[df['CityId'].isin([1, 5])]

# Select the desired columns using loc
selected_df = filtered_df.loc[:, ['Id', 'Gender', 'AgeGroup', 'AnnualIncome', 'CreditScore', 'Spending Score']] 

# Display the filtered and selected data
print(selected_df)

   Id Gender AgeGroup  AnnualIncome  CreditScore  Spending Score
0   1   Male    18-24         30000          700              75
4   5   Male    35-44         50000          800              95


<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;">8.A. Write a code to show the boxplot of CustomerGender against SpendingScore and wirte your inferences on the difference in gender. [use seaborn](3 marks)

<span style="font-family: Arial; font-weight:bold;font-size:1.5em;color:#0a7a78;">8. B. Plot the correlation heatmap of the dataset and write the inferences. (2 Marks)