<b>Please note today we have some continuation from session 4</b>

In [15]:
# Convert the string 'UVWXY' to a list
result = list('UVWXY')
print(result)


['U', 'V', 'W', 'X', 'Y']


In [2]:


# importing the libraries
import numpy as np
import pandas as pd

In [39]:
nd_array=np.arange(1,101,25).reshape(1,4)

In [41]:
nd_array


array([[ 1, 26, 51, 76]])

In [29]:
#concatenate 2 array should be of same shape

In [3]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
newarray=np.concatenate([a,b]).reshape(2,4)
newarr2=np.arange(11,19).reshape(2,4)
print(newarray)
print('♦♦')
print(newarr2)
#concatenating column wise
np.concatenate([newarray,newarr2],axis=1)

[[1 2 3 4]
 [5 6 7 8]]
♦♦
[[11 12 13 14]
 [15 16 17 18]]


array([[ 1,  2,  3,  4, 11, 12, 13, 14],
       [ 5,  6,  7,  8, 15, 16, 17, 18]])

In [7]:
np.concatenate([newarray,newarr2],axis=0) #concatenating row wise

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [8]:
c=np.hstack([newarray,newarr2]) #This is equivalent to concatenation along the second axis (for 2D arrays, axis = 1

In [9]:
c

array([[ 1,  2,  3,  4, 11, 12, 13, 14],
       [ 5,  6,  7,  8, 15, 16, 17, 18]])

In [10]:
d=np.vstack([newarray,newarr2]) #This is equivalent to concatenation along the first axis (for 2D arrays, axis = 0)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [11]:
# Concatenate 1D arrayTwo or more arrays will get joined along existing (first) axis,
# provided they have the same shape, except in the dimension corresponding to the axis 
# (i.e. for 1D array, the shape can be different along the first axis)
x=np.array([1,4,5,7])
y=np.array([6,9,3])
z=np.array([2,7,5,9])
np.concatenate([x,y,z])


array([1, 4, 5, 7, 6, 9, 3, 2, 7, 5, 9])

In [12]:
d.ndim

2

In [13]:
e=np.dstack([newarray,newarr2])
e

array([[[ 1, 11],
        [ 2, 12],
        [ 3, 13],
        [ 4, 14]],

       [[ 5, 15],
        [ 6, 16],
        [ 7, 17],
        [ 8, 18]]])

In [80]:
e.ndim

3

In [86]:
e.shape

(2, 4, 2)

In [100]:
arr=np.arange(9)
print(np.split(arr,3))
arr2=np.arange(10)
print('array_split',np.array_split(arr2,3)) ##it gives option to split element even when it is not equally divisble
print(np.array_split(arr2,[1,4,8]))## 1,4,8 refers index so anything before it ex before 4 and after 0 means 1,2,3


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
array_split [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([0]), array([1, 2, 3]), array([4, 5, 6, 7]), array([8, 9])]


In [14]:
array_1=np.array([[1,3,5,7],[2,4,6,8]])

In [15]:
array_1.shape

(2, 4)

In [17]:
print(array_1)

[[1 3 5 7]
 [2 4 6 8]]


In [19]:
split_array = np.hsplit(array_1, 2)
split_array2 = np.vsplit(array_1, 2)

In [20]:
split_array2

[array([[1, 3, 5, 7]]), array([[2, 4, 6, 8]])]

In [116]:
split_array

[array([[1, 3],
        [2, 4]]),
 array([[5, 7],
        [6, 8]])]

In [21]:
split_array.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [126]:
# # The reason split_array.ndim gives an error is that split_array is not an array itself;
# it's actually a list of arrays created by np.hsplit. Since split_array is a Python list, 
# it does not have an ndim attribute.

# # To check the dimensions of each sub-array within split_array, 
# you would need to access the individual arrays in the list. For example:

In [124]:
print(split_array[0].ndim)


2


Iterating through an Array

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr)

(2, 3)
2
[[1 2 3]
 [4 5 6]]


In [130]:
for element in np.nditer(arr):
    print(element)

1
2
3
4
5
6


In [24]:
# Simple iteration using a for loop
for row in arr:
    for element in row:
        print(element)

1
2
3
4
5
6


In [25]:
for row in arr:
    print(row*2)

[2 4 6]
[ 8 10 12]


In [26]:
for row in arr:
    print(row*2)

[2 4 6]
[ 8 10 12]


In [27]:
result = []

for row in arr:
    result.append(row * 2)

print(result)

[array([2, 4, 6]), array([ 8, 10, 12])]


In [142]:
result2 = np.array(result)
print(result2)

[[ 2  4  6]
 [ 8 10 12]]


In [144]:
result2.shape


(2, 3)

In [89]:
print(arr)
print(np.arange(1,7).reshape(2,3))
result3 = np.array([row * 2 for row in arr])
print(result3)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


# PANDAS

In [28]:
# creating a list of price of different medicines
med_price_list = [55,25,75,40,90,100]
series_arr = pd.Series(med_price_list)
series_arr

0     55
1     25
2     75
3     40
4     90
5    100
dtype: int64

In [29]:
l1=[1,2,3,4]
series_arr2 = pd.Series(l1)
series_arr2

0    1
1    2
2    3
3    4
dtype: int64

In [30]:
pd.Series(l1, index=['A','B','C','D']) 

A    1
B    2
C    3
D    4
dtype: int64

In [31]:
t=(1,2,3,4)
pd.Series(t,index=['x','y','z','x1'])

x     1
y     2
z     3
x1    4
dtype: int64

In [32]:
d={'A':10,'B':20,'C':20}

In [33]:
data=pd.Series(d)
data['A']

np.int64(10)

In [34]:
pd.Series(d)['A']


np.int64(10)

In [35]:
a=pd.Series(np.arange(1,10))
print(a)
type(pd.Series(a))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64


pandas.core.series.Series

In [36]:
a


0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [37]:
a=pd.Series(np.arange(1,10),index=list('ABCDEFGHI'))

In [38]:
a

A    1
B    2
C    3
D    4
E    5
F    6
G    7
H    8
I    9
dtype: int64

In [78]:
drr=[
    {'A':10,'B':20,'C':20},
    {'D':10,'E':20,'F':20}
]
print('data\n',pd.Series(drr))
type(pd.Series(drr))

data
 0    {'A': 10, 'B': 20, 'C': 20}
1    {'D': 10, 'E': 20, 'F': 20}
dtype: object


pandas.core.series.Series

In [40]:
pd.Series(drr)[0]

{'A': 10, 'B': 20, 'C': 20}

In [41]:
pd.DataFrame(drr)

A     B     C     D     E     F
0  10.0  20.0  20.0   NaN   NaN   NaN
1   NaN   NaN   NaN  10.0  20.0  20.0

In [81]:
a=pd.Series(np.arange(1,10),index=np.arange(100,109))
b=pd.Series(np.arange(1,10),index=np.arange(100,109)) ## note even custom indexes should be same for arthimetic operations
a

100    1
101    2
102    3
103    4
104    5
105    6
106    7
107    8
108    9
dtype: int64

In [43]:
a*b

100     1
101     4
102     9
103    16
104    25
105    36
106    49
107    64
108    81
dtype: int64

In [44]:
a//b

100    1
101    1
102    1
103    1
104    1
105    1
106    1
107    1
108    1
dtype: int64

In [45]:
reformedData=pd.DataFrame({'Sum':a+b,'Exponents':a**b})
reformedData

Sum  Exponents
100    2          1
101    4          4
102    6         27
103    8        256
104   10       3125
105   12      46656
106   14     823543
107   16   16777216
108   18  387420489

In [84]:
print(a[100])
a[100]

1


np.int64(1)

In [47]:
a

100    1
101    2
102    3
103    4
104    5
105    6
106    7
107    8
108    9
dtype: int64

In [48]:
# Extract values at indices 103 (for 4), 105 (for 6), and 107 (for 8)
extracted_values = a[[103, 105, 107]]

# Display the extracted values
print(extracted_values)

103    4
105    6
107    8
dtype: int64


In [49]:
a.sort_values(ascending=False)

108    9
107    8
106    7
105    6
104    5
103    4
102    3
101    2
100    1
dtype: int64

In [50]:
a.sort_index(ascending=False)

108    9
107    8
106    7
105    6
104    5
103    4
102    3
101    2
100    1
dtype: int64

In [51]:
a.values

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a.items

<bound method Series.items of 100    1
101    2
102    3
103    4
104    5
105    6
106    7
107    8
108    9
dtype: int64>

In [53]:
a.index

Index([100, 101, 102, 103, 104, 105, 106, 107, 108], dtype='int64')

In [54]:
a.keys

<bound method Series.keys of 100    1
101    2
102    3
103    4
104    5
105    6
106    7
107    8
108    9
dtype: int64>

In [55]:
a[0:5]

100    1
101    2
102    3
103    4
104    5
dtype: int64

In [56]:
a[100]

np.int64(1)

In [57]:
a


100    1
101    2
102    3
103    4
104    5
105    6
106    7
107    8
108    9
dtype: int64

In [58]:
a[100:105]

Series([], dtype: int64)

In [59]:
z=pd.DataFrame(np.arange(5,25),index=np.arange(0,20))


In [60]:
z


0
0    5
1    6
2    7
3    8
4    9
5   10
6   11
7   12
8   13
9   14
10  15
11  16
12  17
13  18
14  19
15  20
16  21
17  22
18  23
19  24

In [61]:
z2=pd.DataFrame({'x':np.arange(5,25)},index=np.arange(0,20))

In [62]:
z2


x
0    5
1    6
2    7
3    8
4    9
5   10
6   11
7   12
8   13
9   14
10  15
11  16
12  17
13  18
14  19
15  20
16  21
17  22
18  23
19  24

In [63]:
a=pd.DataFrame([1,2,3,4,5],columns=['ABC'])

In [64]:
a


ABC
0    1
1    2
2    3
3    4
4    5

In [65]:
newTable=pd.DataFrame(np.arange(1,26).reshape(5,5),index=list('UVWXY'),columns=['A','B','C','D','E'])

In [66]:
newTable

A   B   C   D   E
U   1   2   3   4   5
V   6   7   8   9  10
W  11  12  13  14  15
X  16  17  18  19  20
Y  21  22  23  24  25

In [67]:
list('UVWXY')

['U', 'V', 'W', 'X', 'Y']

In [68]:
ser=pd.Series(['India','Bhutan','Srilanka'],index=[1,4,9])

In [69]:
ser


1       India
4      Bhutan
9    Srilanka
dtype: object

In [70]:
ser.reindex(np.arange(15)) # note in rest of the places it is doing Nan

0          NaN
1        India
2          NaN
3          NaN
4       Bhutan
5          NaN
6          NaN
7          NaN
8          NaN
9     Srilanka
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
dtype: object

In [71]:
ser

1       India
4      Bhutan
9    Srilanka
dtype: object

In [72]:
ser[0]='USA'

In [73]:
ser


1       India
4      Bhutan
9    Srilanka
0         USA
dtype: object

In [74]:
ser_reindexed=ser.reindex(np.arange(15),fill_value='Bangalore')
ser_reindexed

0           USA
1         India
2     Bangalore
3     Bangalore
4        Bhutan
5     Bangalore
6     Bangalore
7     Bangalore
8     Bangalore
9      Srilanka
10    Bangalore
11    Bangalore
12    Bangalore
13    Bangalore
14    Bangalore
dtype: object

In [75]:
ser_reindexed=ser.reindex(np.arange(15),method='ffill')
ser_reindexed

ValueError: index must be monotonic increasing or decreasing

In [422]:
ser_reindexed=ser.reindex(np.arange(15),method='bfill')
ser_reindexed

0        India
1        India
2       Bhutan
3       Bhutan
4       Bhutan
5     Srilanka
6     Srilanka
7     Srilanka
8     Srilanka
9     Srilanka
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
dtype: object

In [424]:
ser_reindexed=ser.reindex(np.arange(15),method='nearest')
ser_reindexed

0        India
1        India
2        India
3       Bhutan
4       Bhutan
5       Bhutan
6       Bhutan
7     Srilanka
8     Srilanka
9     Srilanka
10    Srilanka
11    Srilanka
12    Srilanka
13    Srilanka
14    Srilanka
dtype: object

In [426]:
newTable=pd.DataFrame(np.arange(1,26).reshape(5,5),index=list('UVWXY'),columns=list('ABCDE'))

In [428]:
newTable

A   B   C   D   E
U   1   2   3   4   5
V   6   7   8   9  10
W  11  12  13  14  15
X  16  17  18  19  20
Y  21  22  23  24  25

In [ ]:
"""In this definition:

Data Source: A list of dictionaries is used, where each dictionary represents a row, and each key-value pair represents a column and its value.
Structure: Each dictionary is treated as a separate row, so:
{'Maths': 10, 'Science': 20, 'Social': 20, 'English': 20} becomes the row for Anil.
{'Maths': 30, 'Science': 20, 'Social': 56, 'English': 55} becomes the row for Rohit.
{'Maths': 40, 'Science': 55, 'Social': 66, 'English': 55} becomes the row for Karthik.
Index: The index is set to ['Anil', 'Rohit', 'Karthik'], so the rows are labeled accordingly."""

In [474]:
newTable=pd.DataFrame([
     {'Maths':10,'Science':20,'Social':20,'English':20},
    {'Maths':30,'Science':20,'Social':56,'English':55},
    {'Maths':40,'Science':55,'Social':66,'English':55}
],index=['Anil','Rohit','Karthik'])
print(newTable)

         Maths  Science  Social  English
Anil        10       20      20       20
Rohit       30       20      56       55
Karthik     40       55      66       55


In [476]:
for index, row in newTable.iterrows():
    print(index)
    # Add 5 to each value in the row
    newTable.loc[index] = row + 5

print(newTable)

Anil
Rohit
Karthik
         Maths  Science  Social  English
Anil        15       25      25       25
Rohit       35       25      61       60
Karthik     45       60      71       60


In [454]:
 newTable.loc['Anil']

Maths      15
Science    25
Social     25
English    25
Name: Anil, dtype: int64

In [464]:
type( newTable.loc['Anil'])
newTable['Maths']# column accessing


Anil       20
Rohit      40
Karthik    50
Name: Maths, dtype: int64

In [482]:
newTable.loc['Anil']

Maths      15
Science    25
Social     25
English    25
Name: Anil, dtype: int64

In [478]:
# Set all values in 'Maths' greater than 20 to 0
newTable.loc[newTable['Maths'] > 20, 'Maths'] = 0
print(newTable)

         Maths  Science  Social  English
Anil        15       25      25       25
Rohit        0       25      61       60
Karthik      0       60      71       60


In [486]:
newTable.loc[newTable['Maths'] == 0, 'Science'] = 0
print(newTable)

         Maths  Science  Social  English
Anil        15       25      25       25
Rohit        0        0      61       60
Karthik      0        0      71       60


In [494]:
newTable=pd.DataFrame(
    {'Maths':[10,20,20],
     'Science':[10,20,20],
     'Social':[10,20,20],
       'English':[10,20,20]}
,index=['Anil','Rohit','Karthik'])

In [496]:
newTable

Maths  Science  Social  English
Anil        10       10      10       10
Rohit       20       20      20       20
Karthik     20       20      20       20

In [ ]:
"""In above definition:

Data Source: A dictionary of lists is used, where each key represents a column, and each list represents the values for that column.
Structure: Each list within the dictionary is treated as a column, so:
Maths column has values [10, 20, 20] for Anil, Rohit, and Karthik.
Science column has values [10, 260, 20].
Social column has values [10, 240, 260].
English column has values [180, 270, 20].
Index: The index is set the same way, ['Anil', 'Rohit', 'Karthik'], so the rows are labeled accordingly.
"""

"""Summary of Differences
Structure: In the first approach, each row is created as a dictionary (useful if rows have varying keys), while in the second approach, each column is created as a list.
Data Layout: The two methods produce different DataFrame structures because the values in each row and column are different.
Use Case:
Use a list of dictionaries when you want to define data row-by-row.
Use a dictionary of lists when you want to define data column-by-column."""