In [3]:
import numpy as np

arr_3d = np.array([
    [[1, 2, 3], 
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12], 
     [13, 14, 15],
     [16, 17, 18]]
])


In [3]:
arr_3d


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
# # Example 1: Select the Entire Second Block (Matrix)
# Explanation:

# 1 in the first position selects the second block (index 1).
# : in the second position means all rows in this block.
# : in the third position means all columns.
print(arr_3d[1,:,:])

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [9]:
# Example 2: Select the First Row from Each Block
Explanation:

# : in the first position means all blocks.
# 0 in the second position selects the first row in each block.
# : in the third position means all columns in that row.
# This returns a 2D array with the first row from each block:
print(arr_3d[:,0,:])

[[ 1  2  3]
 [10 11 12]]


In [5]:
# Example 3: Select the Last Row of the First Block
# Explanation:

# 0 in the first position specifies the first block.
# -1 in the second position selects the last row.
# : in the third position means all columns in that row.
# This gives us the last row of the first block as a 1D array:
result = arr_3d[0, -1, :] #efficient  u might not always no the array dimensions
print(result)

print('alternative',arr_3d[0,2,:])

[7 8 9]
alternative [7 8 9]


In [11]:
# Example 4: Select a Specific Element (e.g., Element 14 in the Second Block)
# 1 in the first position specifies the second block.
# 1 in the second position selects the second row within the second block.
# 1 in the third position selects the second column in that row.
# This gives us the element 14:
print(arr_3d[1,1,1])

14


In [17]:
"""
Example 5: Select a 2x2 Subarray from the Top-Left Corner of the Second Block
Explanation:

1 in the first position specifies the second block.
:2 in the second position selects the first two rows (rows 0 and 1) within this block.
:2 in the third position selects the first two columns (columns 0 and 1) within those rows.
This returns a 2x2 subarray from the top-left corner of the second block:
"""
print(arr_3d[1,0:2,0:2])

print('o/p✔✔✔✔✔',arr_3d[1,:2,:2])


[[10 11]
 [13 14]]
o/p✔✔✔✔✔ [[10 11]
 [13 14]]


In [21]:
"""
Example 6: Select the Middle Column from Each Block
Explanation:

: in the first position means all blocks.
: in the second position means all rows.
1 in the third position selects the middle column (column 1) in each row.
This gives us a 2D array with the middle column from each block:
"""
print('o/p✔✔✔✔✔',arr_3d[:,:,1])

o/p✔✔✔✔✔ [[ 2  5  8]
 [11 14 17]]


In [25]:
"""
Example 7: Select All Elements Except the Last Column in Each Block
Explanation:

: in the first position means all blocks.
: in the second position means all rows.
:-1 in the third position means all columns except the last one.
"""
print('o/p✔✔✔✔✔',arr_3d[:,:,:2])
print('o/p🚀🚀🚀🚀🚀🚀🚀',arr_3d[:,:,:-1])

o/p✔✔✔✔✔ [[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]]
o/p🚀🚀🚀🚀🚀🚀🚀 [[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]]


In [27]:
"""
Example 8: Select All Elements in the Last Row of Each Block
Explanation:

: in the first position means all blocks.
-1 in the second position selects the last row in each block.
: in the third position means all columns in that row.
This results in a 2D array containing the last row from each block:
"""
print('o/p🚀🚀🚀🚀🚀🚀🚀',arr_3d[:,-1,:])

o/p🚀🚀🚀🚀🚀🚀🚀 [[ 7  8  9]
 [16 17 18]]


In [33]:
"""
Example 9: Select All Elements in the First Column of Each Block Except the First Row
Explanation:

: in the first position means all blocks.
1: in the second position selects all rows except the first (starting from row 1).
0 in the third position selects the first column in each row.
This returns a 2D array with the elements from the first column of each block, excluding the first row:
"""
print('o/p✔✔✔✔',arr_3d[:,1:,0]) #better approach
print('o/p🚀🚀🚀🚀🚀🚀🚀',arr_3d[:,1:,:1])

o/p✔✔✔✔ [[ 4  7]
 [13 16]]
o/p🚀🚀🚀🚀🚀🚀🚀 [[[ 4]
  [ 7]]

 [[13]
  [16]]]
