In [3]:
import numpy as np

In [27]:
array1=np.array([10,20,30,40,50,60,70,80,90])
print(array1[0])
print(array1[-1])

10
90


In [5]:
print(array1[-4])

20


In [7]:
print(array1[-1:-6:-2])# every second element

[50 30 10]


In [31]:
print(array1[-1:-8:-3])# every 3rd element

[90 60 30]


In [7]:
array2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(array2d)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [25]:
print(array2d[1, 2])
# Explanation
# array2d[1, 2] refers to:
# Row 1 (the second row, because indexing starts from 0).
# Column 2 (the third column, because indexing starts from 0).

60


In [17]:
print(array2d[1:2])

[[40 50 60]]


Understanding the Slice array2d[1:2]
When you use array2d[1:2], you’re slicing the array along the first axis (rows) and specifying that you want to include only rows from index 1 up to (but not including) index 2.

1:2 means "start at row index 1 and end before row index 2," which will select only row 1 (the second row) in the array.
Result of array2d[1:2]
Since it includes only row 1, the output will be a 2D array containing only that row:

Explanation of the Output
The output [[40 50 60]] is still a 2D array, but it contains only the second row ([40, 50, 60]).
The result is [[40, 50, 60]] (a 2D array with shape (1, 3)) rather than [40, 50, 60] (a 1D array with shape (3,)) because slicing in this way retains the two-dimensional structure.
Summary
array2d[1:2] extracts a subarray containing only row 1.
The resulting subarray has shape (1, 3), indicating it’s a 2D array with one row and three columns.

In [21]:
#If you want to extract just the elements 40 and 50 from the 2D array, you can access
#them using slicing across both rows and columns.
# To get the elements 40 and 50 (which are located in the second row, first and second columns), you can use this code:

# Extract elements 40 and 50
result = array2d[1, 0:2]
print(result)
# Explanation of the Code
# array2d[1, 0:2]:
# 1 selects the second row (index 1).
# 0:2 selects the first two columns (columns at index 0 and 1).



[40 50]


In [27]:
array2d[0,:] 
# The expression array2d[0, :] is a way to select all columns in a
# specific row (in this case, row 0) in a 2D NumPy array.
# Explanation of array2d[0, :]
# 0 (in the row position) means "select row 0" (the first row, since indexing starts from 0).
# : (colon in the column position) means "select all columns."
# So, array2d[0, :] will select all columns in row 0, resulting in a 1D array with the elements from the first row.

array([10, 20, 30])

In [31]:
#The expression array2d[:, 1] is a way to select all rows for a specific column (in this case, column 1) in a 2D NumPy array. 
# Here’s how it works with an example.
array2d[:,1]
# Explanation of array2d[:, 1]
# : (colon in the row position) means "select all rows."
# 1 (in the column position) means "select column 1" (the second column, because indexing starts from 0).
# So, array2d[:, 1] will select all rows in column 1, resulting in a 1D array with the elements from the second column.

array([20, 50, 80])

In [11]:
array2d[0:2,1:3]

array([[20, 30],
       [50, 60]])

In [15]:
type(array2d[0:2,1:3])

numpy.ndarray

In [17]:
# -1 writing is necessary of u want to reverse


NameError: name 'shape' is not defined

In [25]:
array1[-1:-3:-1]

array([50, 40])