In [2]:
import numpy as np

In [ ]:
array1=np.array([10,20,30,40,50,60,70,80,90])
print(array1[[0,2,4]])# accessing multiple elements of a series
print(array1[0])
print(array1[-1])

[10 30 50]
10
90


In [5]:
print(array1[-4])

20


In [7]:
print(array1[-1:-6:-2])# every second element

[50 30 10]


In [31]:
print(array1[-1:-8:-3])# every 3rd element

[90 60 30]


In [3]:
array2d=np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
print(array2d)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [25]:
print(array2d[1, 2])
# Explanation
# array2d[1, 2] refers to:
# Row 1 (the second row, because indexing starts from 0).
# Column 2 (the third column, because indexing starts from 0).

60


In [6]:
print(array2d[1:2,:2])

[[40 50]]


Understanding the Slice array2d[1:2]
When you use array2d[1:2], you’re slicing the array along the first axis (rows) and specifying that you want to include only rows from index 1 up to (but not including) index 2.

1:2 means "start at row index 1 and end before row index 2," which will select only row 1 (the second row) in the array.
Result of array2d[1:2]
Since it includes only row 1, the output will be a 2D array containing only that row:

Explanation of the Output
The output [[40 50 60]] is still a 2D array, but it contains only the second row ([40, 50, 60]).
The result is [[40, 50, 60]] (a 2D array with shape (1, 3)) rather than [40, 50, 60] (a 1D array with shape (3,)) because slicing in this way retains the two-dimensional structure.
Summary
array2d[1:2] extracts a subarray containing only row 1.
The resulting subarray has shape (1, 3), indicating it’s a 2D array with one row and three columns.

In [21]:
#If you want to extract just the elements 40 and 50 from the 2D array, you can access
#them using slicing across both rows and columns.
# To get the elements 40 and 50 (which are located in the second row, first and second columns), you can use this code:

# Extract elements 40 and 50
result = array2d[1, 0:2]
print(result)
# Explanation of the Code
# array2d[1, 0:2]:
# 1 selects the second row (index 1).
# 0:2 selects the first two columns (columns at index 0 and 1).



[40 50]


In [27]:
array2d[0,:] 
# The expression array2d[0, :] is a way to select all columns in a
# specific row (in this case, row 0) in a 2D NumPy array.
# Explanation of array2d[0, :]
# 0 (in the row position) means "select row 0" (the first row, since indexing starts from 0).
# : (colon in the column position) means "select all columns."
# So, array2d[0, :] will select all columns in row 0, resulting in a 1D array with the elements from the first row.

array([10, 20, 30])

In [31]:
#The expression array2d[:, 1] is a way to select all rows for a specific column (in this case, column 1) in a 2D NumPy array. 
# Here’s how it works with an example.
array2d[:,1]
# Explanation of array2d[:, 1]
# : (colon in the row position) means "select all rows."
# 1 (in the column position) means "select column 1" (the second column, because indexing starts from 0).
# So, array2d[:, 1] will select all rows in column 1, resulting in a 1D array with the elements from the second column.

array([20, 50, 80])

In [11]:
array2d[0:2,1:3]

array([[20, 30],
       [50, 60]])

In [15]:
type(array2d[0:2,1:3])

numpy.ndarray

In [9]:
# -1 writing is necessary of u want to reverse


In [25]:
array1[-1:-3:-1]

array([50, 40])

In [17]:

print(array1)
print('steps example',array1[::2] )#in steps of 2)

[10 20 30 40 50 60 70 80 90]
steps example [10 30 50 70 90]


In [19]:
print('steps example',array1[::3] )#in steps of 3)

steps example [10 40 70]


In [21]:
print('steps example',array1[::-1] )#reverse)

steps example [90 80 70 60 50 40 30 20 10]


In [23]:
print(array2d) #2d slicing example

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [25]:
print(array2d[1,]) # row with index 1 all columns

[40 50 60]


In [27]:
print(array2d[:,1]) # first columns

[ 20  50  80 110]


In [29]:
print(array2d[1:3,1:3]) 

[[50 60]
 [80 90]]


In [31]:
print(array2d[1:3,]) # all elements of1st and 2nd row

[[40 50 60]
 [70 80 90]]


In [33]:
print(array2d[:,1:3])  # all elements of1st and 2nd column

[[ 20  30]
 [ 50  60]
 [ 80  90]
 [110 120]]


In [37]:
print(array2d[1:3,1]) # 1st and 2nd rowbut only column 1

[50 80]


In [39]:
print(array2d[1:3,:1]) # 1st and 2nd row and 0th column

[[40]
 [70]]


In [41]:
print(array2d[1:3,1:]) 

[[50 60]
 [80 90]]


In [5]:
# Creating a 3D array (matrix) with 2 rows and 3 columns
arr_3d = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]],[[1, 2, 3], [4, 5, 6],[7, 8, 9]]])

# Print the 2D array
print("3D Array:")
print(arr_3d)
print(arr_3d.ndim)
arr_3d.shape

3D Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


(2, 3, 3)

###### arr_3d[0]

In [7]:
# The shape (2, 3, 3) describes a 3-dimensional array with three axes, and it can be interpreted as:

# 2: The number of blocks or matrices along the first axis.
# 3: The number of rows in each 2D matrix along the second axis.
# 3: The number of columns in each row along the third axis.
# So, (2, 3, 3) is read as:

# An array of 2 matrices,
# Each matrix has 3 rows and 3 columns.

In [77]:
# Example Slices:
# 1. Selecting the First Block (Matrix) Only
# To select the entire first block (index 0 along the first axis):
# Explanation:

# 0: Specifies the first block (index 0) along the first axis.
# : (colon) in the second axis position means "all rows."
# : (colon) in the third axis position means "all columns."
# Thus, arr_3d[0, :, :] extracts all rows and columns from the first block, resulting in the full 3x3 matrix:
result = arr_3d[0, :, :]
print(result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
arr_3d[0]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
# 2. Selecting the Second Row of Each Block
# To select the second row from each 3x3 matrix in the array:
#Explanation: arr_3d[:, 1, :] selects the second row (index 1) from each block (both blocks).
# Explanation:

# : in the first position means "all blocks."
# 1: Specifies the second row (index 1) within each block.
# : in the third position means "all columns."
# This results in a 2D array showing the second row from each block:
result2 = arr_3d[:, 1, :]
print(result2)


[[4 5 6]
 [4 5 6]]


In [23]:
result3=arr_3d[:, 1:3, :]
print(result3)
result3.shape

[[[4 5 6]
  [7 8 9]]

 [[4 5 6]
  [7 8 9]]]


(2, 2, 3)

In [39]:
# 3. Selecting the First Column of Each Block
# To select the first column from each 3x3 matrix in the array:
# Explanation:

# : in the first position means "all blocks."
# : in the second position means "all rows."
# 0: Specifies the first column in each row.
# This results in a 2D array showing the first column from each block:
result4 = arr_3d[:, :, 0]
print(result4.ndim)
print('Shape🚀🚀🚀🚀🚀🚀',result4.shape)
print(result4)


2
Shape🚀🚀🚀🚀🚀🚀 (2, 3)
[[1 4 7]
 [1 4 7]]


In [81]:
# 4. Selecting a Specific Element (e.g., Element 5 in the First Block)
# To select the element 5 in the first block (located at row 1, column 1):
# Explanation:

# 0: Specifies the first block (index 0).
# 1: Specifies the second row (index 1) within the first block.
# 1: Specifies the second column (index 1) within that row.
result5 = arr_3d[0, 1, 1]
print(result5)
print('Shape🚀🚀🚀🚀🚀🚀',result5.shape)


5
Shape🚀🚀🚀🚀🚀🚀 ()


In [55]:
arr_3d[1, 2, 2]

9

In [57]:
arr_3d[:, 2, 2]

array([9, 9])

In [63]:
# 5. Selecting a 2x2 Subarray from the First Block
# To select a smaller 2x2 subarray from the top-left corner of the first block:
# Explanation:

# 0: Specifies the first block.
# :2 in the second position selects the first two rows (index 0 and 1).
# :2 in the third position selects the first two columns (index 0 and 1) within those rows.
# This results in a 2x2 subarray from the top-left corner of the first block:
arr_3d[0, :2, :2]

array([[1, 2],
       [4, 5]])

In [71]:
# 6. Selecting the Last Column of the Second Block
# To select only the last column of the second block:
# Explanation:

# 1: Specifies the second block (index 1).
# : in the second position means "all rows."
# -1: Specifies the last column in each row.
# This returns the last column of the second block as a 1D array:
arr_3d[1, :, -1]

array([[3],
       [6],
       [9]])

In [73]:
# Summary of Slicing Patterns
# arr_3d[0, :, :]: Selects an entire block.
# arr_3d[:, 1, :]: Selects a specific row from each block.
# arr_3d[:, :, 0]: Selects a specific column from each block.
# arr_3d[0, 1, 1]: Selects a single element.
# arr_3d[0, :2, :2]: Selects a 2x2 subarray within a block.
# arr_3d[1, :, -1]: Selects the last column in the second block.