1D NumPy Array
A single row of values (like a list).

In [1]:
import numpy as np

# 1D NumPy array
array_1d = np.array([10, 20, 30, 40, 50])
print(array_1d)


[10 20 30 40 50]


Shape: (5,) (1 dimension with 5 elements).

2D NumPy Array
A matrix with rows and columns.

In [2]:
# 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Shape: (3, 3) (3 rows and 3 columns).

3D NumPy Array
A stack of 2D matrices (like a cube of numbers).

In [3]:
# 3D NumPy array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Shape: (2, 2, 2) (2 matrices, each 2x2).

pandas Series
A 1D labeled array, like a NumPy array with row labels (index).

In [4]:
import pandas as pd

# pandas Series
series = pd.Series([100, 200, 300, 400], index=['A', 'B', 'C', 'D'])
print(series)


A    100
B    200
C    300
D    400
dtype: int64


Shape: (4,) (1D with labels).

pandas DataFrame
A 2D labeled data structure, like a table with rows and columns.

In [1]:
# pandas DataFrame
dataframe = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Salary": [50000, 60000, 70000]
})
print(dataframe)


<IPython.core.display.Javascript object>

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000


Shape: (3, 3) (3 rows and 3 columns).