In [1]:
import numpy as np

In [5]:
arr_zeros=np.zeros(shape=4 ,dtype=int)
arr_zeros

array([0, 0, 0, 0])

In [6]:
arr_ones=np.ones(shape=4,dtype=int)
arr_ones

array([1, 1, 1, 1])

In [8]:
arr_random=np.random.random(size=10)
arr_random

array([0.54059326, 0.56564509, 0.93306443, 0.70593395, 0.3539178 ,
       0.33367746, 0.84509745, 0.93111198, 0.34830523, 0.7154883 ])

In [12]:
arr_arange=np.arange(1,20,2,dtype=float)
arr_arange

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [17]:
print(arr_arange.dtype)
print(arr_arange.shape)
arr_arange.ndim

float64
(10,)


1