In [1]:
import numpy as np

In [2]:
import numpy as np

# Define the matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Element-wise multiplication
element_wise_product = A * B 
print("Element-wise Product:\n", element_wise_product)

# Dot product (matrix multiplication)
dot_product = np.dot(A, B) 
print("Dot Product:\n", dot_product) 

# Alternative for dot product using @ operator
matrix_product = A @ B
print("Matrix Product (using @):\n", matrix_product)

Element-wise Product:
 [[ 5 12]
 [21 32]]
Dot Product:
 [[19 22]
 [43 50]]
Matrix Product (using @):
 [[19 22]
 [43 50]]


In [3]:
import numpy as np

# Generate an array of 5 evenly spaced values between 0 and 1
x = np.linspace(0, 1, 5) 
print(x)  # Output: [0.  0.25 0.5  0.75 1. ]

# Generate an array of 10 values between -1 and 1, excluding the endpoint
y = np.linspace(-1, 1, 10, endpoint=False)
print(y)  # Output: [-1.         -0.81818182 -0.63636364 -0.45454545 -0.27272727 -0.09090909  0.09090909  0.27272727  0.45454545  0.63636364]

[0.   0.25 0.5  0.75 1.  ]
[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8]


In [5]:
arr_zeros=np.zeros(shape=4 ,dtype=int)
arr_zeros

array([0, 0, 0, 0])

In [6]:
arr_ones=np.ones(shape=4,dtype=int)
arr_ones

array([1, 1, 1, 1])

In [8]:
arr_random=np.random.random(size=10)
arr_random

array([0.54059326, 0.56564509, 0.93306443, 0.70593395, 0.3539178 ,
       0.33367746, 0.84509745, 0.93111198, 0.34830523, 0.7154883 ])

In [12]:
arr_arange=np.arange(1,20,2,dtype=float)
arr_arange

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [17]:
print(arr_arange.dtype)
print(arr_arange.shape)
arr_arange.ndim

float64
(10,)


1

What is enumerate()?

enumerate() is a built-in function in Python that adds a counter to an iterable (like a list, tuple, string, etc.).
It returns an enumerate object, which can be iterated over to get pairs of values:
The index (counter)
The corresponding value from the original iterable.

In [1]:
my_list = ['apple', 'banana', 'cherry']

for index, fruit in enumerate(my_list):
    print(f"Index: {index}, Fruit: {fruit}")

Index: 0, Fruit: apple
Index: 1, Fruit: banana
Index: 2, Fruit: cherry


Counter starts from 0 by default: The index starts at 0 for the first element.

Can be customized: You can specify a starting value for the counter using the start parameter:

In [2]:
for index, fruit in enumerate(my_list, start=1): 
    print(f"Index: {index}, Fruit: {fruit}")

Index: 1, Fruit: apple
Index: 2, Fruit: banana
Index: 3, Fruit: cherry


# Heirarchical Indexing

In [4]:
import pandas as pd
ser1=pd.Series([1,2,3,4,5,6],index=[[1,1,1,2,2,2],['a','b','c','a','b','c']])
ser1

1  a    1
   b    2
   c    3
2  a    4
   b    5
   c    6
dtype: int64

In [6]:
ser1.index.names=['index1','index2']
ser1

index1  index2
1       a         1
        b         2
        c         3
2       a         4
        b         5
        c         6
dtype: int64

In [7]:
ser1[1]

index2
a    1
b    2
c    3
dtype: int64

In [8]:
ser1[:, 'a']

index1
1    1
2    4
dtype: int64

In [9]:
pwd


'c:\\Users\\11040026\\Documents\\GitHub\\python-Basics\\Self Learning'

In [11]:
import pandas as pd
path_file=r'c:\Users\11040026\Documents\GitHub\python-Basics\Self Learning\weather.csv'
uk=pd.read_csv(path_file)
uk

date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [15]:
import pandas as pd

# Sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
        'Age': [25, 30, 25, 22, 30],
        'City': ['New York', 'London', 'Paris', 'New York', 'London']}
df = pd.DataFrame(data)
print(df)

# Group by 'Name' and calculate the average age for each name
grouped_df = df.groupby('Name')['Age'].mean() 

print(grouped_df)
df.groupby('Name')['Age'].nunique()

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2    Alice   25     Paris
3  Charlie   22  New York
4      Bob   30    London
Name
Alice      25.0
Bob        30.0
Charlie    22.0
Name: Age, dtype: float64


Name
Alice      1
Bob        1
Charlie    1
Name: Age, dtype: int64

groupby() is a powerful method in pandas. It allows you to group your DataFrame based on one or more columns.

Aggregation:

After grouping, you can apply aggregation functions to each group. Common aggregation functions include:

sum(): Calculate the sum of values within each group.

mean(): Calculate the average of values within each group.

min(): Find the minimum value within each group.

max(): Find the maximum value within each group.

count(): Count the number of rows within each group.

std(): Calculate the standard deviation within each group.

first(), last(): Get the first or last value within each group.


In [14]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
        'Age': [25, 30, 25, 22, 30],
        'City': ['New York', 'London', 'Paris', 'New York', 'London']}
df = pd.DataFrame(data)

# Count unique values in each column
unique_counts = df.nunique()
print(unique_counts)

Name    3
Age     3
City    3
dtype: int64
