In [1]:
import numpy as np

In [5]:
arr_zeros=np.zeros(shape=4 ,dtype=int)
arr_zeros

array([0, 0, 0, 0])

In [6]:
arr_ones=np.ones(shape=4,dtype=int)
arr_ones

array([1, 1, 1, 1])

In [8]:
arr_random=np.random.random(size=10)
arr_random

array([0.54059326, 0.56564509, 0.93306443, 0.70593395, 0.3539178 ,
       0.33367746, 0.84509745, 0.93111198, 0.34830523, 0.7154883 ])

In [12]:
arr_arange=np.arange(1,20,2,dtype=float)
arr_arange

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [17]:
print(arr_arange.dtype)
print(arr_arange.shape)
arr_arange.ndim

float64
(10,)


1

What is enumerate()?

enumerate() is a built-in function in Python that adds a counter to an iterable (like a list, tuple, string, etc.).
It returns an enumerate object, which can be iterated over to get pairs of values:
The index (counter)
The corresponding value from the original iterable.

In [1]:
my_list = ['apple', 'banana', 'cherry']

for index, fruit in enumerate(my_list):
    print(f"Index: {index}, Fruit: {fruit}")

Index: 0, Fruit: apple
Index: 1, Fruit: banana
Index: 2, Fruit: cherry


Counter starts from 0 by default: The index starts at 0 for the first element.

Can be customized: You can specify a starting value for the counter using the start parameter:

In [2]:
for index, fruit in enumerate(my_list, start=1): 
    print(f"Index: {index}, Fruit: {fruit}")

Index: 1, Fruit: apple
Index: 2, Fruit: banana
Index: 3, Fruit: cherry
