**Packages**
 - Collections of multiple functions
 - These are stored in the backend
 - Numpy - for all sorts of numerical operations
 - Pandas - for tabular data manipulations
 - Seaborn , Matplotlib - Data Visualization

In [4]:
sqrt(100)
#python doesn't recognize sqrt

NameError: name 'sqrt' is not defined

In [30]:
import math #default packages in python

In [18]:
math.sqrt(100)

10.0

In [20]:
import math as m #aliasing

In [22]:
m.sqrt(169)

13.0

In [24]:
from math import sqrt

In [26]:
sqrt(144)

12.0

In [28]:
from m import sqrt
#m is nothing in backend"

ModuleNotFoundError: No module named 'm'

**Numpy**
- Mathematical operations are possible in numpy due to numpy array data structure

In [1]:
import numpy as np

In [7]:
l1=[10,20,30]

In [8]:
l2=[100,200,300]

In [12]:
l1+l2

[10, 20, 30, 100, 200, 300]

**Numpy arrays**
- used to convert list into different data structure, using this entire mathematical part becomes easy

In [15]:
arr1 = np.array(l1)

In [17]:
arr2 = np.array(l2)

In [19]:
arr1

array([10, 20, 30])

In [21]:
type(arr1)

numpy.ndarray

ndarray - n dimensional array

In [24]:
arr2

array([100, 200, 300])

In [26]:
type(arr2)

numpy.ndarray

In [28]:
arr1+arr2 # Mathematical operations is happening

array([110, 220, 330])

**Characteristics of Numpy Array**
- It allows multiple dimensions
- Very easy to perform arithmatic operations, and fast
- Array if of only one data type (int / float / boolean)

In [31]:
t1=(10,20,30)
np.array(t1)

array([10, 20, 30])

In [33]:
arr1.ndim #Dimension

1

In [35]:
l1

[10, 20, 30]

In [37]:
l2

[100, 200, 300]

In [39]:
l=[l1,l2]

In [41]:
l # This is a nested list

[[10, 20, 30], [100, 200, 300]]

In [43]:
type(l) # nested list

list

In [45]:
arr= np.array(l)

In [47]:
arr

array([[ 10,  20,  30],
       [100, 200, 300]])

In [49]:
type(arr)

numpy.ndarray

In [51]:
arr.ndim # 2 D Array

2

In [97]:
arr.shape

(2, 3)

In [99]:
arr.size


6

In [101]:
arr.itemsize

4

In [103]:
l3=[10,20]
l4=[10]

In [105]:
np.array([l3,l4])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [107]:
l3=[10,20]
l4=[13,12]

In [109]:
np.array([l3,l4])

array([[10, 20],
       [13, 12]])

In [113]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [115]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
a.ndim

2

In [119]:
a.shape

(3, 3)

Data is all 2D, images are 3D

In [128]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9],[1,2,3],[4,5,6],[7,8,9]]])

In [130]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [132]:
a.ndim

3

In [134]:
range(10)

range(0, 10)

In [138]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [142]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [150]:
np.arange(1,10).reshape(3,3) #changing 1D to 2D using reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [152]:
np.arange(1,9).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [154]:
a=np.arange(1,101).reshape(10,10)

In [160]:
a
#indices

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [158]:
a.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [162]:
a[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [164]:
a[2:7]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [168]:
a[::2] #start:stop+1:step

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [170]:
#[Row,Col]
#[start:stop+1:step,start:stop+1:step]

In [172]:
a[:,0] #1D

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [176]:
a[:,[0]] #2D

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [178]:
a[1:3,0]

array([11, 21])

In [180]:
a[:,1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [182]:
a[:,1:1]

array([], shape=(10, 0), dtype=int32)

In [184]:
a[2:8,1:4]

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74]])

In [186]:
a[2:8][1:4]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [55]:
arr1=np.array((10,20))
arr2=np.array((10,20))
arr1+arr2

array([20, 40])

In [57]:
type(arr1+arr2)

numpy.ndarray

In [67]:
#Array Indexing

In [69]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [71]:
a=np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [73]:
#Select :32,33 to 62,63

In [75]:
a[3:7,1:3]

array([[32, 33],
       [42, 43],
       [52, 53],
       [62, 63]])

In [79]:
a[3:7, 3:8]

array([[34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58],
       [64, 65, 66, 67, 68]])

In [87]:
a[5:9,[3,5,7]]

array([[54, 56, 58],
       [64, 66, 68],
       [74, 76, 78],
       [84, 86, 88]])

In [89]:
a[5:9,3:8:2]

array([[54, 56, 58],
       [64, 66, 68],
       [74, 76, 78],
       [84, 86, 88]])

In [91]:
a[0][0]

1

In [93]:
a[1][1]

12

In [95]:
a.diagonal()

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [97]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [99]:
#Transpose

In [101]:
a.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [105]:
b=np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [107]:
b.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [113]:
#is a.T same as a[::-1,::-1]

In [115]:
a.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [117]:
a[::-1,::-1]

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

**Fancy Indexing**

In [128]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [130]:
a[[1,5,8]]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [132]:
a[[1,2,2,4,2,1]]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [134]:
a[3:8,[3,5,7]]

array([[34, 36, 38],
       [44, 46, 48],
       [54, 56, 58],
       [64, 66, 68],
       [74, 76, 78]])

In [140]:
a[[1,2,3],[1,2,3]]

array([12, 23, 34])

In [146]:
a[[1,2,3],[1,2,3]]

array([12, 23, 34])

In [148]:
#Operations in Array

In [150]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [152]:
a+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [154]:
a-2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [158]:
a*2.2

array([[ 2.2,  4.4,  6.6,  8.8],
       [11. , 13.2, 15.4, 17.6],
       [19.8, 22. , 24.2, 26.4]])

In [162]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,1])

In [164]:
a+b

array([3, 5, 7, 5])

In [166]:
a-b

array([-1, -1, -1,  3])

In [168]:
a*b

array([ 2,  6, 12,  4])

In [170]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,1,5])

In [172]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [174]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [176]:
b=a+10

In [178]:
b

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [180]:
a+b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [182]:
a=np.arange(1,7).reshape(3,2)

In [184]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [186]:
b=a.T

In [188]:
a@b

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [190]:
a.dot(b)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [194]:
np.matmul(a,b)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [196]:
a.mean()

3.5

In [198]:
np.mean(a)

3.5

In [200]:
a.std()

1.707825127659933

In [202]:
a.min()

1

In [204]:
a.max()

6

In [206]:
np.exp(a)

array([[  2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003],
       [148.4131591 , 403.42879349]])

In [208]:
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947]])

In [212]:
np.round(np.log(a),2)

array([[0.  , 0.69],
       [1.1 , 1.39],
       [1.61, 1.79]])

In [214]:
np.sum(a)

21

In [216]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [218]:
a.mean()

3.5

In [220]:
a.mean(0)

array([3., 4.])

In [222]:
a.mean(1)

array([1.5, 3.5, 5.5])

In [224]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [226]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [228]:
np.zeros(5, dtype='int32')

array([0, 0, 0, 0, 0])

In [234]:
np.zeros([3,3], dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [236]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [238]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [240]:
#random  - sub module in numpy

In [244]:
np.random.randint(5,25,10)

array([15,  7,  8, 21, 12,  5, 17, 17, 13, 13])

In [246]:
np.random.randint(5,25,10)

array([15, 11, 21, 20, 24, 17, 20, 11, 17,  8])

In [251]:
np.random.randint(1,7,15) #dice

array([3, 3, 3, 6, 3, 6, 4, 5, 2, 6, 6, 6, 4, 5, 1])

In [253]:
from numpy.random import randint

In [255]:
randint(1,6,5)

array([5, 1, 2, 4, 5])

In [259]:
np.random.randn(10)# for std normal deviation, mean =0, std dev=1

array([ 0.94137817, -0.04642363,  0.57766139,  1.73479911,  0.92759858,
       -0.01605406, -1.51742814,  0.21990133,  1.15111242,  0.45865681])

In [263]:
a=np.random.randn(1000)

In [267]:
np.mean(a)

0.00374849550774891

In [269]:
np.std(a)

1.0085193291568149

#Exercise

MSE1 - 10 students, take random marks

MSE2 - 10 students, take random marks

avg

results

In [22]:
mse1=np.random.randint(1,101,10)
mse1

array([60,  1, 13, 84, 74, 50, 32, 38, 41, 74])

In [23]:
mse2=np.random.randint(1,101,10)
mse2

array([86, 72, 79,  6,  6, 70, 22, 47, 91, 72])

In [24]:
(mse1+mse2)/2

array([73. , 36.5, 46. , 45. , 40. , 60. , 27. , 42.5, 66. , 73. ])

In [28]:
#take best of two from the two arrays

In [283]:
np.max((mse1,mse2),axis=0)

array([95, 30, 53, 79, 51, 55, 50, 64, 92, 98])

In [287]:
# Any and All

In [3]:
a=np.array([True, True, True])
b=np.array([True, False, True])
c=np.array([False, False, False])

In [4]:
np.any(a)

True

In [5]:
np.all(a)

True

In [9]:
np.any(b)

True

In [10]:
np.all(b)

False

In [14]:
np.any(c)

False

In [16]:
np.all(c)

False

In [30]:
mse1<40

array([False,  True,  True, False, False, False,  True,  True, False,
       False])

**Where in Python**

In [33]:
#conditional replacement

In [37]:
a=np.array([1,2,3,4])
b=np.array([100,200,300,400])
c=np.array([True, False,True,False])

In [39]:
np.where(c,a,b)

array([  1, 200,   3, 400])

In [41]:
mse1

array([60,  1, 13, 84, 74, 50, 32, 38, 41, 74])

In [43]:
mse2

array([86, 72, 79,  6,  6, 70, 22, 47, 91, 72])

In [45]:
np.where(mse2<40,mse1,mse2)

array([86, 72, 79, 84, 74, 70, 32, 47, 91, 72])

In [47]:
np.where(mse2<40,40,mse2)

array([86, 72, 79, 40, 40, 70, 40, 47, 91, 72])

In [49]:
for mark in mse1:
    print("score is ",mark)

score is  60
score is  1
score is  13
score is  84
score is  74
score is  50
score is  32
score is  38
score is  41
score is  74


In [53]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [61]:
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [63]:
#Stacking

In [65]:
a=np.array([1,2,3])
b=np.array([10,20,30])

In [69]:
np.hstack((a,b))

array([ 1,  2,  3, 10, 20, 30])

In [71]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [10, 20, 30]])

In [73]:
np.column_stack((a,b))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [75]:
np.dstack((a,b))

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]]])

In [77]:
#Concatenate

In [79]:
a

array([1, 2, 3])

In [81]:
b

array([10, 20, 30])

In [85]:
np.concatenate((a,b))

array([ 1,  2,  3, 10, 20, 30])

In [87]:
np.concatenate((a,b), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [91]:
c=np.arange(1,7).reshape(2,3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
d=c+10
d

array([[11, 12, 13],
       [14, 15, 16]])

In [95]:
np.concatenate([c,d],axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [97]:
np.concatenate([c,d],axis=1)


array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])