<ul style="background:yellow; color: darkblue;
  margin: 5px size=6;">
<li>
1. NumPy Arrays (ndarray)
ndarray is the core data structure of NumPy, which stands for "n-dimensional array." Unlike Python lists, which can hold heterogeneous data types, NumPy arrays are homogeneous (i.e., they contain elements of the same type).
NumPy arrays are more memory-efficient and provide faster operations than Python lists, especially for large datasets.
</li
    <li>
        2. Dynamic and Flexible Data Structures
Python Lists: Lists are dynamically sized. You can easily append, insert, or remove elements. They are ideal when you need a flexible data structure whose size changes over time.
NumPy Arrays: Arrays are more rigid. Resizing them (e.g., adding new elements) is less efficient because it involves creating a new array and copying the data.
    </li>
    <li>
        3. Associative Data with Dictionaries
Python Dictionaries: Dictionaries are key-value pairs, which allow you to associate data with specific keys, making them very useful for fast lookups by key. NumPy does not provide a structure equivalent to this; it focuses on numerical computation where keys are typically indices (positions).
    </li>>
</ul>

The numpy.arange() function in NumPy generates arrays with evenly spaced values within a given range. It's similar to Python’s built-in range() function but returns a NumPy array rather than a list, and it provides additional flexibility, like specifying non-integer steps (floats).
Python Lists and Dictionaries: Both lists and dictionaries are more flexible and better suited for handling arbitrary or non-numerical data, such as strings, objects, or complex data structures.
NumPy Arrays: Designed for numerical data and cannot easily handle arbitrary Python objects without losing performance advantages.

In [13]:
!pip install numpy

In [15]:
# The first step of using numpy is to tell Python to import it
import numpy as np

In [23]:
arr_num = [5, 4, 6, 7]
arr_num_np=np.array(arr_num)
arr_np=np.array([1,2,3,4])
print(arr_np)
print(arr_num_np)

[1 2 3 4]
[5 4 6 7]


In [31]:
cmb_arr_np=arr_num_np+arr_np # array size should match
print(cmb_arr_np)

[ 6  6  9 11]


In [35]:
cmb_arr_np=arr_num_np*arr_np

In [37]:
cmb_arr_np

array([ 5,  8, 18, 28])

In [39]:
cmb_arr_np.ndim # dimension of arr

1

In [41]:
cmb_arr_np.shape

(4,)

In [43]:
cmb_arr_np.size

4

In [53]:
arr_num3 = [5, 4, 6, 7,8]
arr_num3_np=np.array(arr_num3)
# size in bites each ele take
print('returns length of each element of array in bytes', arr_num3_np.itemsize)
print('length of arr',arr_num3_np.size)

 returns length of each element of array in bytes 4
length of arr 5


In [71]:
arr_num4_np=np.array([1.5,2,3,4,5],dtype="int") #explicit casting to int
print(arr_num4_np)
print(arr_num4_np.itemsize)
arr_num4_np.dtype

[1 2 3 4 5]
4


dtype('int32')

In [67]:
arr_num5_np=np.array([1.5,2,3,4,5],dtype="int16")
print(arr_num5_np)
print(arr_num5_np.itemsize)
arr_num5_np.dtype

[1 2 3 4 5]
2


dtype('int16')

In [73]:
# Creating a 2D array (matrix) with 2 rows and 3 columns
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Print the 2D array
print("2D Array:")
print(arr_2d)

2D Array:
[[1 2 3]
 [4 5 6]]


In [91]:
reshaped_array=arr_2d.reshape(3,2)
print(reshaped_array)
reshaped_array.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [87]:
# Indexing 2D array
a12=reshaped_array[0][1] #1st row 2nd column

In [89]:
a12

2

In [99]:
arr_3d2 = np.array([[[1,2,3]]])
print(arr_3d2.ndim)
arr_3d2.shape

3


(1, 1, 3)

In [107]:
# Creating a 3D array (matrix) with 2 rows and 3 columns
arr_3d = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]],[[1, 2, 3], [4, 5, 6],[7, 8, 9]]])

# Print the 2D array
print("3D Array:")
print(arr_3d)
print(arr_3d.ndim)
arr_3d.shape
# 2 represents stacks of rows

3D Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


(2, 3, 3)

In [134]:
arr_32d = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]],[[1, 2, 3], [4, 5, 6],[7, 8, 9]],[[1, 2, 3], [4, 5, 6],[7, 8, 9]]])

# Print the 2D array
print("3D Array:")
print(arr_32d)
print(arr_32d.ndim)
arr_32d.shape

"""
In the shape (3, 3, 3):

The first 3 represents the number of matrices or 2D arrays (or depth in a 3D structure).
The second 3 represents the number of rows in each 2D array.
The third 3 represents the number of columns in each 2D array.
Thus, this is a 3D array with:

3 layers (or matrices),
Each layer having 3 rows, and
Each row having 3 columns.
"""

3D Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


'\nIn the shape (3, 3, 3):\n\nThe first 3 represents the number of matrices or 2D arrays (or depth in a 3D structure).\nThe second 3 represents the number of rows in each 2D array.\nThe third 3 represents the number of columns in each 2D array.\nThus, this is a 3D array with:\n\n3 layers (or matrices),\nEach layer having 3 rows, and\nEach row having 3 columns.\n'

In [111]:
np.arange(1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [262]:
# Create an array of letters (both lowercase and uppercase)
letters = np.array(list('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'))

# Generate a single random letter
random_letter = np.random.choice(letters)
print(random_letter)

g


In [264]:


# Create a 2D NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])


data = arr[::2]  # This takes every 2nd row, starting from index 0

print(data)


[[1 2 3]
 [7 8 9]]


In [119]:
x=np.arange(1,21).reshape(4,5)

In [156]:
print('x-->⬆',x)

print('**')
print(x[1:3])
print('*##*')
x[0:3]

x-->⬆ [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
**
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
*##*


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [194]:
x[1:3,1:3]  # [row:column]  so 1:3 extracts row and 1:3 after comma extracts column

array([[ 7,  8],
       [12, 13]])

In [200]:
in_np=np.arange(1,101).reshape(10,10)
in_np

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [218]:
in_np[3:8]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [232]:
in_np[3:8,2:7:2] #arr[::2]: This slices the array, taking every second row, effectively skipping the rows in between.
#strees of word second

array([[33, 35, 37],
       [43, 45, 47],
       [53, 55, 57],
       [63, 65, 67],
       [73, 75, 77]])

In [234]:
in_np[1,5]

16

In [238]:
# all zeroes
np.zeros((5,4),dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [240]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [246]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [250]:
np.full((4,5),77)

array([[77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77]])

In [260]:
a=np.arange(0,25).reshape(5,5)
print(a)
n_fullLike=np.full_like(a,100)
n_fullLike

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [266]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [270]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [274]:
np.eye(7,k=1)

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [276]:
np.eye(7,k=2) #observe the shifting

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [284]:
a2='Somnath'

In [286]:
a2[0]

'S'

In [290]:
a2[::-1]

'htanmoS'

In [294]:
nl=np.arange(1,10).reshape(3,3)
nl


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [298]:
nl.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [304]:
nl[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [308]:
nl[::-1]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [310]:
xy=[1,2,3,4,5,6]
xy[::-1]

[6, 5, 4, 3, 2, 1]

In [312]:
xy[::-3]

[6, 3]

In [322]:
gen_arr=np.ones((5,5),dtype='int')
gen_arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [326]:
gen_arr2=np.zeros((3,3))
gen_arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [328]:
gen_arr2[1,1]=9

In [330]:
gen_arr2

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [336]:
gen_arr[1:4,1:4]=gen_arr2 #update concept

In [334]:
gen_arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [338]:
#statistics -explore on own

In [340]:
stats_ar=np.arange(1,10)
stats_ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [342]:
stats_ar.min()

1

In [344]:
stats_ar.prod()

362880

In [348]:
stats_ar2=np.identity(5,dtype='int')
stats_ar2

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [352]:
np.linalg.det(stats_ar2) ##something mathematical

1.0

In [354]:
stats_ar3=np.arange(1,7).reshape(2,3)
stats_ar3

array([[1, 2, 3],
       [4, 5, 6]])

In [356]:
stats_ar4=np.arange(1,7).reshape(2,3)
stats_ar4

array([[1, 2, 3],
       [4, 5, 6]])

In [358]:
stats_ar4*stats_ar3 #possible as same shape same indexs gets multiplied

array([[ 1,  4,  9],
       [16, 25, 36]])

In [360]:
arr_random=np.random.rand(5)
arr_random

array([0.34237455, 0.19859119, 0.5213961 , 0.64570135, 0.03488647])

In [362]:
arr_random2=np.random.rand(5)
arr_random2

array([0.06764185, 0.82600052, 0.13886495, 0.05463509, 0.75412076])

In [366]:
arr_random3=np.random.randint(5,10,12) #lowvalue,high value and size Press shift tab to see fn def
arr_random3

array([6, 8, 5, 7, 9, 9, 9, 7, 9, 5, 7, 9])

In [368]:
arr_random3.mean()

7.5

In [372]:
arr_random3.sum()

90

In [374]:
arr_random3.std()

1.5

In [376]:
arr_random4=np.random.random(5) 
arr_random4

array([0.07138837, 0.15104888, 0.61520616, 0.83329572, 0.52251974])

In [378]:
m=np.array([True,True,True,True])
n=np.array([True,False,True,False])
o=np.array([False,False,False,False])

In [380]:
m.any()

True

In [388]:
n.any()

True

In [390]:
n.all()

False

In [406]:
p=np.array([1,88,3,4])
q=np.array([2,1,4,2])

In [414]:
np.where(n,p,q) #result comes on basis of n

array([1, 1, 3, 2])

In [398]:
t_np=np.array([10,20,30,40])
t_np

array([10, 20, 30, 40])

In [400]:
t_np[:]>20

array([False, False,  True,  True])

In [424]:
np.where(t_np>20,p,q)

array([2, 1, 3, 4])

In [434]:
stu=np.random.randint(5,90,12).reshape(6,2)
stu


array([[ 9, 54],
       [24, 81],
       [43, 81],
       [11, 45],
       [32, 56],
       [55, 29]])

In [436]:
status=stu[stu>35]
status

array([54, 81, 43, 81, 45, 56, 55])

In [440]:
reformedis=np.random.randint(5,90,15).reshape(5,3) ## pending
reformedis

array([[49, 68, 67],
       [34, 77, 88],
       [58, 44, 13],
       [31, 71, 83],
       [80, 60, 65]])

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [174]:
x[-2:] # to include last element

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [123]:
x2=np.arange(1,21).reshape(2,10)
x2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [127]:
x3=np.arange(1,21).reshape(1,2,10)
x3

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]])

In [129]:
x4=np.arange(1,21).reshape(2,2,5) # changing to 3d array
x4

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [136]:
b=np.array([1,2,3,4,5,6])
b[2:5]

array([3, 4, 5])

In [140]:
x[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:


data = ['a', 'b', 'c', 'd', 'e']
index = np.arange(len(data))
print("Index array:", index)

# Accessing elements using the index array
for i in index:
    print(f"Element at index {i}: {data[i]}")

# When working with data that requires indexing, arange can be used to generate arrays that serve as indices for other arrays or structures.

Index array: [0 1 2 3 4]
Element at index 0: a
Element at index 1: b
Element at index 2: c
Element at index 3: d
Element at index 4: e


In [4]:
import numpy as np

1. Creating Sequences of Numbers
The most common use of arange is to create sequences of numbers for quick iteration or numerical analysis. It’s especially useful when you need an array of numbers to represent time steps, coordinates, indices, etc.

In [23]:


# Creating an array of numbers from 0 to 9
arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [42]:
# You can iterate over a NumPy array using a simple for loop or Python’s flat attribute for arrays.

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Simple iteration using a for loop
for row in arr:
    for element in row:
        print(element)
print("***** nditer *****")
for element in np.nditer(arr):
    print(element)



1
2
3
4
5
6
***** nditer *****
1
2
3
4
5
6


Why Use nditer:
Efficiency: nditer is optimized for performance, especially when dealing with large arrays. It avoids the overhead of multiple loops in Python.
Element-Wise Iteration: Using nditer, you can iterate over arrays element by element, regardless of their shape, without needing nested loops.

In [6]:
# Generate a random array of 5 elements
random_arr = np.random.rand(5)
print(random_arr)


[0.564827   0.46272948 0.99810375 0.01592823 0.55593397]
