<table align="left" width=100%>
    <tr>
        <td width="20%">
            <img src="faculty.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Faculty Notebook <br> (Session 4) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

## Table of Content

1. **[What is Python Numpy](#python_numpy)**
2. **[Functions to Create Array](#functions)**
3. **[Attributes and Functions on Array](#operations)**
4. **[Indexing Array](#Indexing)**
5. **[Slicing Array](#Slicing)**
6. **[Operations on a 1D Array](#operations_1d)**
7. **[Operations on a 2D Array](#operations_2d)**
8. **[Arithmetic Functions in Numpy](#arithmetic_functions)**
9. **[Concatenation of Array](#concatenation)**
10. **[Stacking of Array](#stacking)**
11. **[Splitting of Array](#splitting)**
12. **[Iterating Numpy Array](#Iterating)**

<a id="python_numpy"> </a>
### 1. What is Python Numpy
<table align="left">
    <tr>
        <td width="15%">
            <img src="note.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>NumPy is a python package that stands for ‘Numerical Python’.<br>
                    Numpy is the core library for scientific computing, which contains a powerful n-dimensional array object, provides tools for integrating C, C++, etc.<br>
                    It contains a powerful N-dimensional array object.<br>
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**How to install numpy?**<br>
1. You can use-<br>
`!pip install numpy`<br>
2. You can import it as-<br>
import numpy as np

In [1]:
# import the numpy package as np
import numpy as np

### Python NumPy Array v/s List
We use python numpy array instead of a list because of the below three reasons:
1. Less Memory<br>
2. Fast<br>
3. Convenient

**The N-dimensional array**<br>
A simple way to create an array from data or simple python data structures like a list is to use the array() function.

In the example below, first, create two python lists. Then, create numpy arrays out of the created lists.

In [2]:
# create 2 new lists height and weight
person_height = [5.2,  5.4, 4.4, 4.5, 5.6, 6]
person_weight = [81, 55, 65, 70, 45, 44]

# create 2 numpy arrays from height and weight
person_height = np.array(person_height)
person_weight = np.array(person_weight)

In [3]:
# print 'person_height' array
person_height

array([5.2, 5.4, 4.4, 4.5, 5.6, 6. ])

In [4]:
# print 'person_weight' array
person_weight

array([81, 55, 65, 70, 45, 44])

**Print type of 'person_weight'**

In [5]:
print(type(person_weight))

<class 'numpy.ndarray'>


<a id="functions"> </a>
### 2. Functions to Create Array

**Array of Zeros**<br>
'zeros()' will create a new array of the specified size with the contents filled with zero values. 

In [6]:
# create array of zeros
from numpy import zeros
my_array = zeros([3,2])
print(my_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


**Array of Ones**<br>
'ones()' will create a new array of the specified size with the contents filled with value one.

In [7]:
# create array of ones
from numpy import ones
my_array = ones([5])
print(my_array)

[1. 1. 1. 1. 1.]


**Array of random numbers**<br>
The random() function returns random numbers in the half-open interval [0.0, 1.0)

In [8]:
# create 2D array of 3 rows and 2 columns
my_array = np.random.random(size = (3,2))
my_array

array([[0.80664893, 0.67459684],
       [0.75583427, 0.13688675],
       [0.21135771, 0.78967815]])

**Note:** We can create an array of random integers in the given range using 'randint()' 

**Array using arange() function**<br>
arange() function creates an array of numbers between the given range

In [9]:
# create an array of integers between 0 to 10  
# 'step' returns numbers with given step_size
array1 = np.arange(start = 0, stop = 10, step = 1)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<a id="operations"> </a>
### 3. Attributes and Functions on Array

#### Attributes: It is defined as a specification that defines a property of an object. Attributes of the numpy array do not have parentheses following them

**ndim:**<br>
Returns the dimension (number of axes) of the numpy array

In [10]:
my_array = np.array([(11,32,23),(34,55,46)])
print(my_array.ndim)

2


**itemsize:**<br>
Use the 'itemsize' function to find the space occupied by each element.

In [11]:
my_array = np.array([(5,5,6,2,75,3)])
print(my_array.itemsize)

4


In the above example, every element occupies 4 bytes.

**dtype:**<br>
Use 'dtype' function to print the datatype along with the size in bytes.

In [12]:
array = np.array([(1,2,3)])
print(array.dtype)

int32


**size and shape:**<br>
Use 'size' to find the number of elements in the array and 'shape' to find the number of rows and columns of the array.

In [13]:
array = np.array([(1,2,3,4,5,6)])
print(array.size)
print(array.shape)

6
(1, 6)


#### Functions/method: A method is a function that “belongs to” an object. It takes parameters in the parentheses and returns the modified array. 

**reshape:**<br>
reshape() is used to change the number of rows and columns of an array without changing the data.<br>

<table align="center">
    <td height = '100', width = '400'>
          <img src="Reshape.jpg">
        </td>
</table>

In [14]:
# create an array
array = np.array([(8,9,10),(11,12,13)])
print("original array:", array)

# change the shape
array = array.reshape(3,2)
print("reshape array:", array)

original array: [[ 8  9 10]
 [11 12 13]]
reshape array: [[ 8  9]
 [10 11]
 [12 13]]


<a id="Indexing"> </a>
### 4. Indexing Array

**Indexing in 1 dimension**

In [15]:
# given array
my_array = np.array([11, 22, 33, 24, 57, 473])

print(my_array)

[ 11  22  33  24  57 473]


Each element in the array can be accessed by passing the positional index of the element.

In [16]:
# get the 1st element
# indexing starts from '0'
print(my_array[0]) 

# get the third element
print(my_array[2]) 

11
33


**Indexing in 2 dimensions**

In [17]:
my_array = np.array([[101, 231, 321],
              [412, 512, 622],
              [712, 821, 912]])
my_array

array([[101, 231, 321],
       [412, 512, 622],
       [712, 821, 912]])

We can retrieve an element of the 2D array using two indices i and j - i selects the row, and j selects the column:

In [18]:
# get the element in 3rd row and 2nd column
print(my_array[2, 1])

821


In [19]:
# we can pass ith row and jth column in separate brackets ([])
print(my_array[2][1])

821


**Picking a row or column**        

We can also select a single row or column 

In [20]:
# pick the second row from the array
print(my_array[2])

[712 821 912]


In [21]:
# pick the second column from the array
print(my_array[:,2])

[321 622 912]


<a id="Slicing"> </a>
### 5. Slicing Array

**Slicing a 1D array**

In [22]:
my_array = [101, 121, 112, 123, 114]

In [23]:
# pick the second, third, and fourth element from the array 
new_array = my_array[1:4]  
new_array

[121, 112, 123]

The slice notation specifies a start and end value [start:end], where 'start' is inclusive but 'end' is exclusive.

In [24]:
# first three elements
c = my_array[:3]
c

[101, 121, 112]

In [25]:
# all the elements from 112
d = my_array[2:]    
d

[112, 123, 114]

In [26]:
# get the complete array
e = my_array[:]
e

[101, 121, 112, 123, 114]

**Slicing a 2D array**

In [27]:
my_array = np.array([[101, 131, 122, 113, 143],
               [145, 165, 137, 318, 193],
               [240, 241, 252, 253, 324],
               [225, 126, 727, 928, 129]])

my_array

array([[101, 131, 122, 113, 143],
       [145, 165, 137, 318, 193],
       [240, 241, 252, 253, 324],
       [225, 126, 727, 928, 129]])

In [28]:
# select all rows except 1st
# select 3rd and 4th column
print(my_array[1:,2:4])

[[137 318]
 [252 253]
 [727 928]]


**Note:** The index returns an element of the array, the slice returns a list of elements.

<a id="operations_1d"> </a>
### 6. Operations on a 1D Array

In [29]:
my_array1 = np.array([120,230,310,410,150])
my_array2 = np.arange(5)

Add the two arrays

In [30]:
my_array3 = my_array1 + my_array2
my_array3

array([120, 231, 312, 413, 154])

In [31]:
my_array4 = np.array([1,2,3,5])
my_array1 + my_array4

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

<table align="left">
    <tr>
        <td width="7%">
            <img src="caution.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>If you try to add arrays with the same dimension but a different number of elements, you get an error.
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [32]:
# multiply each element in the array by 4 
my_array1*4

array([ 480,  920, 1240, 1640,  600])

Use ' ** ' to compute power of the numbers.

In [33]:
# get square of each element
my_array1**2

array([ 14400,  52900,  96100, 168100,  22500], dtype=int32)

**Using Numpy with Comparison Expressions**

In [34]:
my_array = np.array([34, 45, 67, 45, 23])

# check which elements are greater than or equal to 40
# the comparison condition gives boolean output
new_array = my_array >= 40
new_array

array([False,  True,  True,  True, False])

Pass the above boolean array to the main array to fetch the values that satisfy the comparison condition.

In [35]:
# elements greater than or equal to 40
my_array[new_array]

array([45, 67, 45])

Rather than creating a separate array of booleans, you can specify the comparison operation directly on the main array.

In [36]:
my_array

array([34, 45, 67, 45, 23])

In [37]:
my_array[my_array >= 40]

array([45, 67, 45])

<a id="operations_2d"> </a>
### 7. Operations on a 2D Array

Let’s create 2 two-dimensional arrays, array_a and array_b.

In [38]:
array_a = np.array([[33,12],[70,61]])
array_b = np.array([[43,51],[72,81]])

In [39]:
print(array_a)
print(array_b)

[[33 12]
 [70 61]]
[[43 51]
 [72 81]]


In [40]:
# add the 2 arrays
array_a + array_b

array([[ 76,  63],
       [142, 142]])

Perform multiplication on array_a and array_b.

In [41]:
array_a*array_b

array([[1419,  612],
       [5040, 4941]])

'+=' operation on the ‘array_a’ is equivalent to adding a specified value to each element of the array. The original array gets modified using this operation.

In [42]:
# add 2 to each element
array_a += 2
array_a

array([[35, 14],
       [72, 63]])

Similarly, you can use other arithmetic operations like -= and *=

In [43]:
# subtract 2 from each element 
array_a -= 2
array_a

array([[33, 12],
       [70, 61]])

In [44]:
# multiply each element by 2 
array_a *= 2
array_a

array([[ 66,  24],
       [140, 122]])

**Matrix Multiplication**<br>

Use '@' operator to perform matrix multiplication (or matrix product).

In [45]:
array_a @ array_b

array([[ 4566,  5310],
       [14804, 17022]])

The same output can also be obtained by the dot().

In [46]:
array_a.dot(array_b)

array([[ 4566,  5310],
       [14804, 17022]])

<a id="arithmetic_functions"> </a>
### 8. Arithmetic Functions in Numpy

In [47]:
# given array
my_array = np.array([5,7,8,2,4])
my_array

array([5, 7, 8, 2, 4])

**sum():**<br>
sum() function adds all the values in the array and gives a scalar output.

In [48]:
# add all the elements of 'my_array'
my_array.sum()

26

**min():**<br>
min function finds the lowest value in the array.

In [49]:
# find minimum of 'my_array'
my_array.min()

2

**power():**<br>
power function raises the numbers in the array to the given value.

In [50]:
# get cube of elements of 'my_array'
np.power(my_array,3)

array([125, 343, 512,   8,  64], dtype=int32)

**Using the axis parameter**<br>
Use the axis parameter with value 0, to find the sum of all the values in a single column.

In [51]:
# create a 2D array of random integers
array1 = np.random.randint(1,10,(2,3))
array1

array([[3, 5, 6],
       [4, 1, 1]])

In [52]:
array1.sum(axis=0)

array([7, 6, 7])

Similarly, to find the lowest value across a particular row, use the axis parameter with a value ‘1'.

In [53]:
array1.min(axis=1)

array([3, 1])

<a id="concatenation"> </a>
### 9. Concatenation of Array

The arrays can be concatenated only if they have same shape, except in the dimension corresponding to the axis of concatenation.

**Concatenate 1D array**

In [54]:
# concatenate two 1D arrays
array_x = np.array([11, 22, 13])
array_y = np.array([23, 22, 12])
np.concatenate([array_x, array_y])

array([11, 22, 13, 23, 22, 12])

You can also concatenate more than two arrays at once.

In [55]:
array_z = np.array([23,45])
print(np.concatenate([array_x, array_y, array_z]))

[11 22 13 23 22 12 23 45]


**Concatenate 2D array**

In [56]:
# create a 2D array
my_array = np.array([[1, 2, 3],
                 [4, 5, 6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

**concatenate along the first axis**

In [57]:
# by default concatenate() is along 'axis = 0'
np.concatenate([my_array, my_array])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

**concatenate along the second axis**

In [58]:
np.concatenate([my_array, my_array], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Concatenate 1D and 2D array**

In [59]:
# concatenate the 1D and 2D arrays
# consider a 1D array -- 'array_x'
# consider a 2D array -- 'my_array'
np.concatenate((array_x, my_array), axis = 0)

ValueError: all the input arrays must have same number of dimensions

**Note:** One can not concatenate the arrays with different dimensions

<a id="stacking"> </a>
### 10. Stacking of Array

Stacking can be used to join 2 or more arrays along the different axis. This method can also be used to create higher-dimensional array using lower dimensional arrays. 
Numpy vstack, Numpy hstack, and Numpy concatenate are all similar functions to join the arrays.

In [60]:
# create two arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
print(array1) 
print(array2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


**NumPy stack** enables you to combine arrays along the specified axis. We can create a higher-dimensional array using stack().

In [61]:
# stack arrays along the 1st axis
array_stack = np.stack((array1, array2), axis=1)
array_stack

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

**NumPy hstack** enables you to combine arrays horizontally.

In [62]:
# stack arrays in sequence horizontally (column wise)
array_h = np.hstack((array1, array2))
array_h

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

**Numpy vstack** enables you to combine arrays vertically.

<table align="center">
    <td width = '250'>
            <img src="vstack.png">
        </td>
</table>

In [63]:
# stack arrays in sequence vertically (row wise)
array_v = np.vstack([array1, array2])
array_v

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**Numpy dstack** will stack arrays along the third axis. It converts each array as the column of the modified array.

In [64]:
# stack arrays in sequence depth wise (along the third axis)
array_d = np.dstack((array1, array2))
array_d

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

**Numpy column_stack** enables you to stack 1D array as 2D array.

In [65]:
# create two 1D array
array1 = np.array([1,4,8])
array2 = np.array([2,5,7])

# stack arrays as 2D array
array_v = np.column_stack([array1, array2])
array_v

array([[1, 2],
       [4, 5],
       [8, 7]])

In [66]:
# check the dimension of stacked array
np.ndim(array_v)

2

**block()** is used to assemble array from a nested list of blocks

In [67]:
# create a block matrix using 1D array

a = np.array([4])
b = np.array([7])
c = np.array([6])
d = np.array([3])

# 2D matrix using block()
np.block([[a,b],
        [c,d]])

array([[4, 7],
       [6, 3]])

<a id="splitting"> </a>
### 11. Splitting of Array

Splitting is used to split the array into multiple sub-arrays. It is opposite of concatenation, which is implemented by the functions like split(), hsplit(), and so on.

<table align="center">
    <td width = '300'>
            <img src="split.png">
</table>

**split():**

In [68]:
# split the array into sub-arrays
array_x = np.arange(8) 
np.split(array_x, 2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

**Split the 1D array at positions indicated**

In [69]:
# the split occurs at 5th and 7th indices
array_y = np.split(array_x,[5,7])
print(array_y)

[array([0, 1, 2, 3, 4]), array([5, 6]), array([7])]


In [70]:
# split 'array_x' into 3 sub-arrays
np.split(array_x, 3)

ValueError: array split does not result in an equal division

<table align="left">
    <tr>
        <td width="7%">
            <img src="caution.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>The split() function does not allow the integer (N) as number of splits, if N does not divide the array into sub-arrays of equal length 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**array_split():** It is used to split the array into sub-arrays. It takes the integer 'N' as the input for the number of splits, even if 'N' does not divide the array into sub-arrays of equal length.<br>

In [71]:
# split 'array_x' into 3 sub-arrays using 'array_split'
np.array_split(array_x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

We split the array of length 8 into 3 sub-arrays; the function 'array_split()' returns <i>8 % 3 (=2)</i> sub-arrays of size <i>8//3 + 1 (=3)</i> and the rest (i.e. one sub-array) of size <i>8//3 (=2)</i>.

**vsplit():**<br>
The vsplit() function is used to split an array into multiple sub-arrays vertically (row-wise).

<table align="center">
        <td height="200", width = '200'>
            <img src="vsplit.png">
        </td>
</table>

In [72]:
my_array = np.arange(20.0).reshape(4,5)
my_array

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [73]:
np.vsplit(my_array, 2)

[array([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]), array([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])]

**hsplit():**<br>
The hsplit() function is used to split an array into multiple sub-arrays horizontally (column-wise).

<table align="center">
    <td width = '100'>
            <img src="hsplit.png">
        </td>
</table>

In [74]:
my_array = np.arange(16.0).reshape(4,4)
my_array

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [75]:
np.hsplit(my_array, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

**dsplit():**<br>
The dsplit() function is used to split an array into multiple sub-arrays.

In [76]:
my_array = np.arange(12.0).reshape (2,2,3)
my_array

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]])

In [77]:
np.dsplit(my_array,3)

[array([[[0.],
         [3.]],
 
        [[6.],
         [9.]]]), array([[[ 1.],
         [ 4.]],
 
        [[ 7.],
         [10.]]]), array([[[ 2.],
         [ 5.]],
 
        [[ 8.],
         [11.]]])]

<a id="Iterating"> </a>
### 12. Iterating Numpy Array

**Iterating a One-dimensional Array**<br>
Iterating one-dimensional array with the use of 'for loop'.

In [78]:
# create 1D array
my_array = np.arange(12)

# add 10 to each element 
for i in my_array:
    print(i+10)

10
11
12
13
14
15
16
17
18
19
20
21


**Iterating a Two-dimensional Array**<br>
If we use the same syntax to iterate a two-dimensional array, we will only be able to iterate a row.

In [79]:
# create a 2D array
my_array = np.arange(12).reshape(4,3)
print(my_array)

# add 11 to each element
for i in my_array:
    print(i+11)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[11 12 13]
[14 15 16]
[17 18 19]
[20 21 22]


**To iterate each element in the two-dimensional array, use the nested for loop.**

In [80]:
for i in my_array:
    for j in i:
        print(j+11)

11
12
13
14
15
16
17
18
19
20
21
22


**nditer() object**<br>
NumPy provides a multi-dimensional iterator object called nditer() to iterate the elements of an array.

In [81]:
# multiply each element in the 2D array by 5
for i in np.nditer(my_array):
    print(i*5)

0
5
10
15
20
25
30
35
40
45
50
55
